### ISSUE TITLE
软件中心下载插件权限问题

### ISSUE THREAD

**Issue by ihuaer** [linkease/istore#1]
在lean openwrt源码中集成该软件中心，但是从软件中心下载插件显示无权限

openwrt用root用户登录

![2021-10-28_181655](https://user-images.githubusercontent.com/12723080/139237481-a23a85e1-ed1e-4539-b8a9-3be69e83b5f9.jpg)

**Comment by jjm2473** [comment]
你不是使用feed的方式加源，而是手动复制代码的吧，复制时又没保留原始权限，那is-opkg就没有可执行权限了

**Comment by ihuaer** [comment]
> 你不是使用feed的方式加源，而是手动复制代码的吧，复制时又没保留原始权限，那is-opkg就没有可执行权限了

可以了，问题解决
