### ISSUE TITLE
点击安装任何一个软件，出现下图，无法关闭，除非重启

### ISSUE THREAD

**Issue by jeffjohncn** [linkease/istore#100]
自己编译的，原版openwrt
<img width="989" alt="屏幕截图 2023-08-12 102910" src="https://github.com/linkease/istore/assets/71160385/de2aae44-a1ca-43ca-9831-c5a7785d79a7">

**Comment by jjm2473** [comment]
按这个重新安装试试 https://github.com/linkease/istore#%E5%AE%89%E8%A3%85-istore-%E5%88%B0-openwrt-%E5%AE%98%E6%96%B9%E5%9B%BA%E4%BB%B6

**Comment by jeffjohncn** [comment]
> 按这个重新安装试试 https://github.com/linkease/istore#%E5%AE%89%E8%A3%85-istore-%E5%88%B0-openwrt-%E5%AE%98%E6%96%B9%E5%9B%BA%E4%BB%B6

是按照这个编译的，出现上述问题，删掉后安装也一样

**Comment by jjm2473** [comment]
不是编译，是让你用那个命令安装

**Comment by jeffjohncn** [comment]
> 不是编译，是让你用那个命令安装

安装过了，结果是一样的，openwrt 23.05版

**Comment by jjm2473** [comment]
OK，我在23.05复现了，应该是23.05的luci有不兼容的逻辑，现在已经绕过了。你更新代码或者重新安装都能修复
