### ISSUE TITLE
 luci-app-ipsec-server  无法安装

### ISSUE THREAD

**Issue by gqbre** [linkease/istore#102]
通过第三方源 openwrt_kiddin9 https://op.supes.top/latest/packages/aarch64_generic 下载，依赖始终不全
~~Collected errors:~~
 ~~* pkg_hash_check_unresolved: cannot find dependency ucode-mod-html for luci-base~~
 ~~* pkg_hash_check_unresolved: cannot find dependency strongswan for luci-app-ipsec-server~~
 ~~* pkg_hash_check_unresolved: cannot find dependency strongswan-minimal for luci-app-ipsec-server~~
 ~~* pkg_hash_check_unresolved: cannot find dependency strongswan-mod-kernel-libipsec for luci-app-ipsec-server~~
 ~~* pkg_hash_check_unresolved: cannot find dependency strongswan-mod-openssl for luci-app-ipsec-server~~
 ~~* pkg_hash_check_unresolved: cannot find dependency strongswan-mod-xauth-generic for luci-app-ipsec-server~~
 ~~* pkg_hash_fetch_best_installation_candidate: Packages for luci-app-ipsec-server found, but incompatible with the architectures configured~~
~~* opkg_install_cmd: Cannot install package luci-app-ipsec-server.~~

剩下个 iptables-mod-ipsec 依赖没找到..

**Comment by jjm2473** [comment]
你反馈的到底跟istore有什么关系？自己手动安装的插件又不是istore提供的。如果是istoreos的问题请到istoreos的issue反馈
