### ISSUE TITLE
istoreos 里面的软件安装不上

### ISSUE THREAD

**Issue by 161424** [linkease/istore#106]
安装环境：Hyper-v

![Snipaste_2023-11-22_20-59-32](https://github.com/linkease/istore/assets/32435360/63d49282-ff50-4e6e-8847-95008ef0062c)
安装过最近的两个版本，都不行

电脑时可以ping通istore.linkease.com，但是在istoreos里面就ping不通了。

咨询过客服、群聊均无一人回应，也百度了，不清楚怎么回事

**Comment by jjm2473** [comment]
1. 网络问题，自己看看ping外网通不通
2. 系统时间不对

**Comment by jjm2473** [comment]
虚拟机的话，建议配置两个虚拟网卡，第一个虚拟网卡选择NAT类型，第二个一般“Host only”就行了。不然的话，单网口的机器默认是LAN口，需要自己配置网关。

**Comment by 161424** [comment]
> 虚拟机的话，建议配置两个虚拟网卡，第一个虚拟网卡选择NAT类型，第二个一般“Host only”就行了。不然的话，单网口的机器默认是LAN口，需要自己配置网关。
我看了一下，时间是对的，我去试试虚拟网卡的方法

**Comment by jjm2473** [comment]
配置虚拟网卡以后要恢复出厂设置才会重新配置网络

**Comment by 161424** [comment]
> 配置虚拟网卡以后要恢复出厂设置才会重新配置网络

我重启了一下电脑网络适配器。安装环境是win11的hyper-v。有两个虚拟网卡，一个连网线，一个连内部。
![Uploading image.png…]()
我是按照  https://sspai.com/post/78201#!  里面配置的，
![Uploading image.png…]()
但是安装好后百度都ping不通

**Comment by 161424** [comment]
> 配置虚拟网卡以后要恢复出厂设置才会重新配置网络

我的实体机网络一点问题都没有，但是虚拟机里面安装的就是没网，因为不能说没网，因为能加载出来istoreos的软件列表

**Comment by jjm2473** [comment]
istore的软件列表是浏览器加载的啊，又不需要路由器又网
