### ISSUE TITLE
随固件编译后默认的源更新失败怎么办

### ISSUE THREAD

**Issue by wgethub** [linkease/istore#107]
`Downloading https://istore.linkease.com/repo/all/compat/Packages.gz
Updated list of available packages in /var/opkg-lists/istore_compat
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/targets/x86/64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/istore/Packages.gz
*** Failed to download the package list from https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/istore/Packages.gz

Downloading https://mirrors.cloud.tencent.com/lede/releases/18.06.9/packages/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony`

`Collected errors:
 * opkg_download: Failed to download https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/istore/Packages.gz, wget returned 8.`

**Comment by jjm2473** [comment]
怎么会有lede？不是openwrt吗？你用的什么固件啊？？

**Comment by jjm2473** [comment]
肯定不是istoreos

**Comment by wgethub** [comment]
> 怎么会有lede？不是openwrt吗？你用的什么固件啊？？

固件是LEDE master的源码，LEDE默认opkg源是腾讯的，看起来好像是源地址有变更，我没找到新的源地址
`aaa@ubuntu:~/lede$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
`

**Comment by jjm2473** [comment]
自带的软件源错误，还不是istoreos，那这关istore屁事啊？
