### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by lukemin** [linkease/istore#11]
把
src-git istore-ui https://github.com/linkease/istore-ui.git
src-git istore https://github.com/linkease/istore.git
加入feeds.conf.default后，编译失败。

[root@instance-20210817-1303 26  /home/ubuntu/lede]$./scripts/feeds update -a && ./scripts/feeds install -a
Syntax error in feeds.conf.default, line 7

**Comment by jjm2473** [comment]
都提示你 feeds.conf.default 第七行语法错误了， “istore-ui”改成“istore_ui” 试试

**Comment by lukemin** [comment]
> 都提示你 feeds.conf.default 第七行语法错误了， “istore-ui”改成“istore_ui” 试试

改了之后，在luci里面没有istore选项

**Comment by jjm2473** [comment]
重新 ./scripts/feeds update -a && ./scripts/feeds install -a 啊，源都变了

**Comment by lukemin** [comment]
> 重新 ./scripts/feeds update -a && ./scripts/feeds install -a 啊，源都变了
feeds.conf.default
`src-git packages https://github.com/coolsnowwolf/packages.git
src-git luci https://github.com/coolsnowwolf/luci.git
src-git routing https://git.openwrt.org/feed/routing.git
src-git telephony https://git.openwrt.org/feed/telephony.git
src-git kenzo https://github.com/kenzok8/openwrt-packages.git
src-git small https://github.com/kenzok8/small.git
src-git istoreui https://github.com/linkease/istore-ui.git
src-git istore https://github.com/linkease/istore.git`
`[root@instance-20210817-1303 33  /home/ubuntu/lede]$git pull
Already up to date.
[root@instance-20210817-1303 34  /home/ubuntu/lede]$ ./scripts/feeds update -a && ./scripts/feeds install -a
Updating feed 'packages' from 'https://github.com/coolsnowwolf/packages.git' ...
Already up to date.
Updating feed 'luci' from 'https://github.com/coolsnowwolf/luci.git' ...
Already up to date.
Updating feed 'routing' from 'https://git.openwrt.org/feed/routing.git' ...
Already up to date.
Updating feed 'telephony' from 'https://git.openwrt.org/feed/telephony.git' ...
Already up to date.
Updating feed 'kenzo' from 'https://github.com/kenzok8/openwrt-packages.git' ...
Already up to date.
Updating feed 'small' from 'https://github.com/kenzok8/small.git' ...
Already up to date.
Updating feed 'istoreui' from 'https://github.com/linkease/istore-ui.git' ...
Already up to date.
Updating feed 'istore' from 'https://github.com/linkease/istore.git' ...
Already up to date.
Create index file './feeds/packages.index' 
Create index file './feeds/luci.index' 
Create index file './feeds/routing.index' 
Create index file './feeds/telephony.index' 
Create index file './feeds/kenzo.index' 
Create index file './feeds/small.index' 
Create index file './feeds/istoreui.index' 
Create index file './feeds/istore.index' 
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.
Installing all packages from feed kenzo.
WARNING: Not overriding core package 'aliyundrive-webdav'; use -f to force
WARNING: Not overriding core package 'luci-app-aliyundrive-webdav'; use -f to force
WARNING: Not overriding core package 'luci-app-jd-dailybonus'; use -f to force
WARNING: Not overriding core package 'luci-app-pushbot'; use -f to force
WARNING: Not overriding core package 'microsocks'; use -f to force
WARNING: Not overriding core package 'redsocks2'; use -f to force
WARNING: Not overriding core package 'UnblockNeteaseMusic'; use -f to force
Installing all packages from feed small.
WARNING: Not overriding core package 'dns2socks'; use -f to force
WARNING: Not overriding core package 'ipt2socks'; use -f to force
WARNING: Not overriding core package 'pdnsd-alt'; use -f to force
Installing all packages from feed istoreui.
Installing all packages from feed istore.
[root@instance-20210817-1303 35  /home/ubuntu/lede]$rm -rf ./tmp && rm -rf .config
[root@instance-20210817-1303 36  /home/ubuntu/lede]$make demenu
`
![微信截图_20211214090922](https://user-images.githubusercontent.com/12003375/145914274-eea762e9-1cf3-478f-ab09-f55ff66cca84.png)
![微信截图_20211214090936](https://user-images.githubusercontent.com/12003375/145914281-4da6c217-4300-40ef-b0c1-91e68db29bd1.png)
![微信截图_20211214090945](https://user-images.githubusercontent.com/12003375/145914282-c8133c53-0117-4a35-9ab7-81470a38cbac.png)
![微信截图_20211214091013](https://user-images.githubusercontent.com/12003375/145914285-7146e883-de68-4735-b2d8-ad834a0ea48e.png)
![1639444129(1)](https://user-images.githubusercontent.com/12003375/145914288-ea7b979b-a3aa-4926-93eb-c169c9e32b0c.jpg)
![微信截图_20211214090910](https://user-images.githubusercontent.com/12003375/145914289-4baa059a-ffc0-432f-8052-8961a969e2ba.png)

**Comment by jjm2473** [comment]
luci-app-store = luci-app + app-store   😆

**Comment by lukemin** [comment]
> luci-app-store = luci-app + app-store 😆

被github的名字误导了，我在luci-app-i开头的app名字那边反复找了好多次。
