### ISSUE TITLE
zerotier-one 无法保存配置

### ISSUE THREAD

**Issue by zctmdc** [linkease/istore#111]
## 存在问题
zerotier-cli 的设置重启丢失
```shell
zerotier-cli set xxxxxxxxxxx  allowGlobal=true
>> zerotier-cli: missing port and zerotier-one.port not found in /var/lib/zerotier-one
```
## 解决办法
1. 创建自启动配置脚本，并设置权限
```shell
echo '
mkdir -p /var/lib/zerotier-one
mount -o bind  /var/lib/zerotier-luci /var/lib/zerotier-one
zerotier-cli set xxxxxxxxxxx   allowGlobal=true
' >> /opt/config_zerotier.sh
chmod +x /opt/config_zerotier.sh
```
2. 添加到开机启动
`sleep 60 &&  /opt/config_zerotier.sh &`
## 替代
`src/gz kiddin9 https://dl.openwrt.ai/packages-23.05/x86_64/kiddin9/`
这个软件源的正常的

**Comment by jjm2473** [comment]
/var是内存盘，肯定不会保存的。

而且，istore不是有插件了吗，为什么不用界面配置？

**Comment by jjm2473** [comment]
千万别用第三方源，要是出问题就别反馈。

**Comment by zctmdc** [comment]
因为 界面没有 allowGlobal

**Comment by zctmdc** [comment]
补充信息：
一开始我用  cli 直接执行的时候 会报错  cli 工具会在  `/var/lib/zerotier-one` 中寻找相关文件与服务通信
```shell
zerotier-cli set xxxxxxxxxxx  allowGlobal=true
>> zerotier-cli: missing port and zerotier-one.port not found in /var/lib/zerotier-one
```
但是执行 `mount -o bind  /var/lib/zerotier-luci /var/lib/zerotier-one` 后就可以正常操作了
```shell
zerotier-cli info
200 info xxxx  1.12.1 ONLINE
```
可见 更新之后 启动程序将 运行时配置放在了 `/var/lib/zerotier-luci` 而不是之前的 `/var/lib/zerotier-one`

我们再看
```shell
ls -al /var/lib/zerotier*
lrwxrwxrwx    1 root     root            16 Jan 22 14:24 /var/lib/zerotier-luci -> /etc/config/zero

/var/lib/zerotier-one:
drwx------    5 root     root          4096 Jan 21 00:36 .
drwxr-xr-x    8 root     root           180 Jan 24 12:28 ..
-rw-------    1 root     root            24 Jan 16 19:50 authtoken.secret
......
-rw-r--r--    1 root     root             5 Jan 22 14:24 zerotier-one.pid
-rw-r--r--    1 root     root             4 Jan 22 14:24 zerotier-one.port
```
可见 luci 位置时放在 /etc 的 所以重启后不会丢失
> /var是内存盘，肯定不会保存的。
> 
> 而且，istore不是有插件了吗，为什么不用界面配置？

可见 luci 位置时放在 /etc 的 所以重启后不会丢失 （我之前配置的时候 只需要设置一次也不会丢失）

```shell
root@HJAJLY:~# cat /etc/init.d/zerotier | grep 'one'
PROG=/usr/bin/zerotier-one
CONFIG_PATH=/var/lib/zerotier-one

root@HJAJLY:~# cat /etc/init.d/zerotier | grep 'luci'

```

**Comment by jjm2473** [comment]
再强调一遍，zerotier的二进制程序不是istore提供的，istore提供的ipk全部在 https://istore.linkease.com/repo/ ，istore只是有个zerotier的luci管理插件而已，如果你都不是使用luci配置的，那怎么样也不会跟istore有关。如果zerotier的二进制程序有问题，那就反馈给openwrt，这是openwrt提供的。不过我更怀疑是你的用法有问题，/var是内存盘，重启肯定不会保存的，如果其中有需要持久化的数据，插件应该会自动创建软链接，但是你手动执行的时候可能就没准备这些了。

**Comment by zctmdc** [comment]
好的 收到啦 谢谢您的解答 感谢您的辛苦付出

**Comment by zzswang** [comment]
@zctmdc 
感谢，解决了命令行一直不能用的问题

**Comment by King-hsw** [comment]
@zctmdc 
`mount -o bind  /var/lib/zerotier-luci /var/lib/zerotier-one`
谢老哥，这行很关键，我系统重置完都不行，你这行很给力
