### ISSUE TITLE
iStore软件商店添加可道云插件

### ISSUE THREAD

**Issue by sangxuesheng** [linkease/istore#112]
可以把可道云插件集成到iStore软件商店里吗
luci-app-kodexplorer
用软件源安装会显示错误

![photo_2024-02-24_17-52-51](https://github.com/linkease/istore/assets/62563207/80d78c55-5cb9-4bf3-bdad-f4b6d02d60b9)

**Comment by jjm2473** [comment]
istore不是有这个插件吗，能不能搜一下再反馈？

**Comment by jjm2473** [comment]
还有，不用使用第三方软件源，要是出问题就自己解决吧，不要反馈。
