### ISSUE TITLE
无论安装什么插件都显示 already running 安装失败,错误码: 1

### ISSUE THREAD

**Issue by Glunefish** [linkease/istore#113]
无论安装什么插件都显示
![image](https://github.com/linkease/istore/assets/27694733/af15a2cc-9039-4d24-a6b8-daac0a56bfd9)

主机名 | CMIOT_AX18
主机型号 | CMIOT AX18
架构 | ARMv8 Processor rev 4 (v8l) x 4 (864MHz, 33.0°C )

Sat Mar  2 21:42:34 2024 kern.info kernel: [    0.000000] Boot CPU: AArch64 Processor [51af8014]

**Comment by Glunefish** [comment]
编译的固件没有包含store中的软件，是精简的OP固件，想通过store安装，发现了这个问题，无法安装任何里面的软件

**Comment by jjm2473** [comment]
可能istore的后台任务卡死了，重启试试。如果重启还这样，那就是istore不支持你的固件。有些国内作者的openwrt衍生固件有procd相关的bug，导致istore的任务管理无法使用。

如果你的固件是istoreos或者原版的openwrt，那可以继续讨论，可能只是因为缺少默认软件包。如果是其他固件，那就不用再反馈了。

**Comment by Glunefish** [comment]
固件是4.4.6内核的op，重启也这样

**Comment by Glunefish** [comment]
默认软件包有哪些？



---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2024年3月4日(周一) 中午1:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [linkease/istore] 无论安装什么插件都显示 already running 安装失败,错误码: 1 (Issue #113)




 
可能istore的后台任务卡死了，重启试试。如果重启还这样，那就是istore不支持你的固件。有些国内作者的openwrt衍生固件有procd相关的bug，导致istore的任务管理无法使用。
 
如果你的固件是istoreos或者原版的openwrt，那可以继续讨论，可能只是因为缺少默认软件包。如果是其他固件，那就不用再反馈了。

**Comment by jjm2473** [comment]
出错以后执行`/etc/init.d/tasks task_status istore`看看输出什么

**Comment by Glunefish** [comment]
执行/etc/init.d/tasks task_status istore 什么都没有 没有内容输出

**Comment by jjm2473** [comment]
那就是procd有bug

**Comment by jjm2473** [comment]
估计又是固件作者自己魔改了procd
