### ISSUE TITLE
安装报错：The requested URL returned error: 404

### ISSUE THREAD

**Issue by wishview** [linkease/istore#116]
![QQ图片20240317161640](https://github.com/linkease/istore/assets/163703645/6f02b876-5026-4c42-9519-f84f6d627cb4)
istore里的所有软件都是这样

**Comment by jjm2473** [comment]
你的设备不是arm64或者x86_64？

**Comment by wishview** [comment]
> 你的设备不是arm64或者x86_64？

ARMv7

**Comment by jjm2473** [comment]
那就不是啊
