### ISSUE TITLE
istore打不开了，网站崩了

### ISSUE THREAD

**Issue by HalcyonDaysssss** [linkease/istore#117]
curl: (7) Failed to connect to istore.linkease.com port 443 after 56 ms: Couldn't connect to server
Collected errors:
 * opkg_download: Failed to download https://istore.linkease.com/repo/all/compat/Packages.gz, curl returned 7.

**Comment by HalcyonDaysssss** [comment]
@jjm2473

**Comment by jjm2473** [comment]
应该恢复了
