### ISSUE TITLE
各种失败啊 安什么软件都失败 是什么问题呢?

### ISSUE THREAD

**Issue by skyheaton** [linkease/istore#122]
![Snipaste_2024-04-30_12-01-00](https://github.com/linkease/istore/assets/63988573/bad5efda-fcac-49fa-9c37-3c1bfc057a0c)
![Snipaste_2024-04-30_12-01-14](https://github.com/linkease/istore/assets/63988573/b9cb500e-5646-4e89-9ce9-a08a7a1bc512)
![Snipaste_2024-04-30_12-01-25](https://github.com/linkease/istore/assets/63988573/7b46ab31-ebca-4c3f-94f7-bdf0892b88df)

**Comment by jjm2473** [comment]
系统软件被你搞坏了呗，`/bin/stat`命令无法执行。

**Comment by breeze303** [comment]
![image](https://github.com/linkease/istore/assets/122870904/4b6764ea-2d8a-41dd-b73c-aa872b7d9ec0)
这个失败怎么解决，自编译的

**Comment by jjm2473** [comment]
500可以看看系统日志，或者浏览器的网络记录

**Comment by breeze303** [comment]
> 500可以看看系统日志，或者浏览器的网络记录

![PixPin_2024-05-06_12-54-41](https://github.com/linkease/istore/assets/122870904/edbf9573-0b8c-4656-8b98-6f23fa1aff43)
找到这个错误了

**Comment by breeze303** [comment]
> > 500可以看看系统日志，或者浏览器的网络记录
> 
> ![PixPin_2024-05-06_12-54-41](https://private-user-images.githubusercontent.com/122870904/328083056-edbf9573-0b8c-4656-8b98-6f23fa1aff43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NzQ4MzYsIm5iZiI6MTcxNDk3NDUzNiwicGF0aCI6Ii8xMjI4NzA5MDQvMzI4MDgzMDU2LWVkYmY5NTczLTBiOGMtNDY1Ni04Yjk4LTZmMjNmYTFhZmY0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQwNTQ4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjRjMjMwM2IwZTEwYmY3NjhiNzIwYTM3YjdhODgzNDM3ODA5NDdiZjJlNjQ4Y2M5Zjc0M2IzMTYyNzhhYjM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pj0UnHm3naLr0YKmIB6wQm31IfH1TiknBREQa2jf-bc) 找到这个错误了

安装luci-lib-ipkg解决了，不知道什么原因导致没有自动勾选上

**Comment by breeze303** [comment]
> @breeze303 istore本来就依赖了luci-lib-ipkg啊，你从哪安装的istore，为什么会没安装luci-lib-ipkg？
> 
> https://github.com/linkease/istore/blob/c43eaae51671ffe995770db5b2fc8af16f5b7a47/luci/luci-app-store/Makefile#L10
> 
> 还有，你的问题跟帖主的不一样。

是自编译的，不清楚为什么mk文件勾选后没有选上，我用的feeds里加了immortalwrt，或许是多个源重复叠加导致的mk错乱，我到时自己维护一个luci和packages算了，非常感谢你的解答，问题已经解决了
![84de46286b214e202a3a595f434573ef](https://github.com/linkease/istore/assets/122870904/086f9dfd-3c6c-493b-9297-6e7b8595710b)

**Comment by breeze303** [comment]
> istore本来就依赖了luci-lib-ipkg啊，你从哪安装的istore，为什么会没安装luci-lib-ipkg？
> 
> https://github.com/linkease/istore/blob/c43eaae51671ffe995770db5b2fc8af16f5b7a47/luci/luci-app-store/Makefile#L10
> 
> 还有，你的问题跟帖主的不一样。

![image](https://github.com/linkease/istore/assets/122870904/eca467eb-c096-4a88-8a0f-d9bccfdf8673)
[kenzok8](https://github.com/kenzok8)，这mk没加。。。

**Comment by jjm2473** [comment]
@breeze303 谁让你用非官方版本呢，他可能是为了兼容自己的老版本luci才去掉的。

**Comment by breeze303** [comment]
> @breeze303 谁让你用非官方版本呢，他可能是为了兼容自己的老版本luci才去掉的。

改用官方了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2278/2
