### ISSUE TITLE
软件商店安装软件报错：Error relocating /bin/stat: statx: symbol not found

### ISSUE THREAD

**Issue by Entruv1** [linkease/istore#123]
错误提示如下：
istore (失败于： 2024/5/2 23:00:27) > is-opkg install 'app-meta-ddnsto'
Error relocating /bin/stat: statx: symbol not found
/bin/is-opkg: line 47: arithmetic syntax error

**Comment by biubiushaka** [comment]
解决了吗就给关闭？

**Comment by jjm2473** [comment]
系统问题啊，又不是我们的固件。

**Comment by jjm2473** [comment]
我们只能保证在openwrt官方版本以及istoreos上能用，其他第三方固件要是不兼容openwrt，只能说关我屁事。

**Comment by xingkong555888** [comment]
我也遇到这个问题了，帮忙看一下是什么问题呗
