### ISSUE TITLE
安装完istore后下载软件的一些问题

### ISSUE THREAD

**Issue by admimare** [linkease/istore#124]
请问高通骁龙410的棒子怎么安装istore 使用命令安装完成无法使用 
使用平台高通骁龙410 
版号 ufi003_mb_v02
报错Error relocating /bin/stat: statx: symbol not found
/bin/is-opkg: line 47: arithmetic syntax error
系统
![image](https://github.com/linkease/istore/assets/74863664/3667cafd-6c97-4431-91e2-86dd0bbb0489)
报错
![image](https://github.com/linkease/istore/assets/74863664/5996cc6f-b227-4bf4-86f3-5ed69af1541e)

**Comment by jjm2473** [comment]
没看到stat命令无法执行吗？

这个平台也不是官方支持的，你从哪个教程看到可以安装istore？

**Comment by xiafeng1128** [comment]
我的X64的平台也出现同样的故障

**Comment by xiafeng1128** [comment]
![image](https://github.com/linkease/istore/assets/37527437/f1082de8-7c5c-45c9-9e73-57bce5530916)
![image](https://github.com/linkease/istore/assets/37527437/4410c538-70c7-4342-a4ea-c4f4b7b41cae)

**Comment by jjm2473** [comment]
算了，既不是istoreos，也不是openwrt。不关心。
