### ISSUE TITLE
R2S: 无法安装istore

### ISSUE THREAD

**Issue by zk36** [linkease/istore#125]
R2S: 
固件版本 OpenWrt 23.05.2 r23630-842932a63d
内核版本 6.1.63

安装istore时无法安装luci-lib-taskd 和 luci-lib-xterm 导致安装失败。

Installing luci-lib-taskd (git-24.310.56389-3018b1f) to root...
Installing luci-lib-xterm (git-24.310.56389-3018b1f) to root...
Collected errors:
 * opkg_download_pkg: Package luci-lib-taskd is not available from any configured src.
 * opkg_install_pkg: Failed to download luci-lib-taskd. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package luci-lib-taskd.
 * opkg_download_pkg: Package luci-lib-xterm is not available from any configured src.
 * opkg_install_pkg: Failed to download luci-lib-xterm. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package luci-lib-xterm.
No packages removed.
Installing luci-app-store (0.1.14-3) to root...
Downloading https://istore.linkease.com/repo/all/store/luci-app-store_0.1.14-3_all.ipk
Installing luci-lib-xterm (git-24.310.56389-3018b1f) to root...
Collected errors:
 * opkg_download_pkg: Package luci-lib-xterm is not available from any configured src.
 * opkg_install_pkg: Failed to download luci-lib-xterm. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package luci-app-store.

**Comment by jjm2473** [comment]
应该是之前用了第三方软件仓库，导致版本号错误无法降级了。恢复出厂设置算了。
