### ISSUE TITLE
请问一下大家,安装遇到这个如何解决（stat，statx）

### ISSUE THREAD

**Issue by LovesLolita** [linkease/istore#129]
<img width="774" alt="image" src="https://github.com/linkease/istore/assets/76564892/69449c69-9477-4172-8688-8fed5e972b0c">

**Comment by LovesLolita** [comment]
<img width="778" alt="image" src="https://github.com/linkease/istore/assets/76564892/a2bb8532-f2a3-415b-9ab0-b7a475ce2c8c">

**Comment by jjm2473** [comment]
找固件作者，问下为什么stat命令没法执行。
