### ISSUE TITLE
打开iStore页面，显示空白

### ISSUE THREAD

**Issue by Cosmos-Break** [linkease/istore#134]
页面空白，刚安装系统的时候是可以的，可能是我进行了某些设置？但是系统日志里面除了singbox没什么异常。
![image](https://github.com/user-attachments/assets/07338b6c-3e82-45a7-adfc-e3151c1fe6ea)

系统日志：
![image](https://github.com/user-attachments/assets/66ebcb21-547c-4449-903b-ee59d2711bc9)

**Comment by jjm2473** [comment]
你用的是istoreos固件？istoreos固件默认怎么是这个主题？

**Comment by jjm2473** [comment]
既然不知道改什么配置导致的异常，那恢复出厂设置，懒得研究。恢复出厂设置以后要是有办法复现，就说明下复现步骤

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3607/1
