### ISSUE TITLE
希望能做一个集成istore的x86固件

### ISSUE THREAD

**Issue by isping7** [linkease/istore#14]

**Comment by jjm2473** [comment]
x86_64可以安装这里的ipk，不过不是所有app都能安装 https://istore.linkease.com/repo/all/store/

**Comment by jannson** [comment]
在制作当中了。。。 请关注我们的 B 站账号：[酷友社](https://space.bilibili.com/1492058311) 会实时发送最新的消息

**Comment by jannson** [comment]
* https://github.com/linkease/istoreos
* https://fw.koolcenter.com/iStoreOS/

已经提供！
