### ISSUE TITLE
R4S安装不了istore增强和路由狗

### ISSUE THREAD

**Issue by zhang-yun-jie** [linkease/istore#140]
‍宝哥, r4s最新版固件我装istoreos增强和路由狗都装不上哎

**Comment by zhang-yun-jie** [comment]
路由狗安装失败的日志: 
Try mirror server https://repo.istoreos.com/repo
Installing app-meta-routerdog (1.4.10-1) to root...
Downloading https://repo.istoreos.com/repo/all/meta/app-meta-routerdog_1.4.10-1_all.ipk
Installing luci-i18n-routerdog-zh-cn (git-24.047.16632-76575fc) to root...
Downloading https://repo.istoreos.com/repo/all/nas_luci/luci-i18n-routerdog-zh-cn_git-24.047.16632-76575fc_all.ipk
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libubox20230523 for opkg
 * check_data_file_clashes: Package luci-i18n-routerdog-zh-cn wants to install file /usr/lib/lua/luci/i18n/routerdog.zh-cn.lmo
        But that file is already provided by package  * luci-app-routerdog
 * opkg_install_cmd: Cannot install package app-meta-routerdog.
Try origin server https://istore.linkease.com/repo
Installing app-meta-routerdog (1.4.10-1) to root...
Downloading https://istore.linkease.com/repo/all/meta/app-meta-routerdog_1.4.10-1_all.ipk
Installing luci-i18n-routerdog-zh-cn (git-24.047.16632-76575fc) to root...
Downloading https://istore.linkease.com/repo/all/nas_luci/luci-i18n-routerdog-zh-cn_git-24.047.16632-76575fc_all.ipk
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libubox20230523 for opkg
 * check_data_file_clashes: Package luci-i18n-routerdog-zh-cn wants to install file /usr/lib/lua/luci/i18n/routerdog.zh-cn.lmo
        But that file is already provided by package  * luci-app-routerdog
 * opkg_install_cmd: Cannot install package app-meta-routerdog.
Fetch feed list for aarch64_generic
Update feeds index
Downloading https://istore.linkease.com/repo/all/nas_luci/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_nas_luci
Downloading https://istore.linkease.com/repo/all/store/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_store
Downloading https://istore.linkease.com/repo/aarch64_cortex-a53/nas/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_nas
Downloading https://istore.linkease.com/repo/all/compat/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/istore_compat
Downloading https://dl.openwrt.ai/latest/packages/aarch64_generic/kiddin9/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_kiddin9
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.7/targets/rockchip/armv8/packages/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_core
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.7/packages/aarch64_generic/base/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_base
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.7/packages/aarch64_generic/luci/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_luci
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.7/packages/aarch64_generic/packages/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_packages
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.7/packages/aarch64_generic/routing/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_routing
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.7/packages/aarch64_generic/telephony/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_telephony
Downloading https://istore.linkease.com/repo/all/meta/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_meta
Try origin server https://istore.linkease.com/repo
Installing app-meta-routerdog (1.4.10-1) to root...
Downloading https://istore.linkease.com/repo/all/meta/app-meta-routerdog_1.4.10-1_all.ipk
Installing luci-i18n-routerdog-zh-cn (git-24.047.16632-76575fc) to root...
Downloading https://istore.linkease.com/repo/all/nas_luci/luci-i18n-routerdog-zh-cn_git-24.047.16632-76575fc_all.ipk
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libubox20230523 for opkg
 * check_data_file_clashes: Package luci-i18n-routerdog-zh-cn wants to install file /usr/lib/lua/luci/i18n/routerdog.zh-cn.lmo
        But that file is already provided by package  * luci-app-routerdog
 * opkg_install_cmd: Cannot install package app-meta-routerdog.

**Comment by jjm2473** [comment]
你使用了非官方的软件源`https://dl.openwrt.ai/latest/packages/aarch64_generic/kiddin9/Packages.gz`，这个软件源的部分软件跟官方软件冲突，所以安装不上。谁让你乱添加第三方软件源的？

**Comment by zhang-yun-jie** [comment]
那我重刷系统试试
