### ISSUE TITLE
安装软件提示失败，但是又能安装上去

### ISSUE THREAD

**Issue by ck-drink** [linkease/istore#144]
Try mirror server https://repo.istoreos.com/repo
Installing app-meta-homebox (1.0.0-1) to root...
Downloading https://repo.istoreos.com/repo/all/meta/app-meta-homebox_1.0.0-1_all.ipk
Installing luci-app-homebox (1.0.1-3) to root...
Downloading https://repo.istoreos.com/repo/all/nas_luci/luci-app-homebox_1.0.1-3_all.ipk
Installing luci-i18n-homebox-zh-cn (git-22.178.38665-ab279f6) to root...
Downloading https://repo.istoreos.com/repo/all/nas_luci/luci-i18n-homebox-zh-cn_git-22.178.38665-ab279f6_all.ipk
Configuring homebox.
Configuring luci-app-homebox.
//usr/lib/opkg/info/luci-app-homebox.postinst: .: line 2: can't open '/etc/uci-defaults/50_luci-homebox': No such file or directory
Configuring luci-i18n-homebox-zh-cn.
//usr/lib/opkg/info/luci-i18n-homebox-zh-cn.postinst: .: line 2: can't open '/etc/uci-defaults/luci-i18n-homebox-zh-cn': No such file or directory
Configuring app-meta-homebox.
Collected errors:
 * pkg_run_script: package "homebox" postinst script returned status 1.
 * opkg_configure: homebox.postinst returned 1.
Try origin server https://istore.linkease.com/repo
Package app-meta-homebox (1.0.0-1) installed in root is up to date.
Configuring homebox.
Collected errors:
 * pkg_run_script: package "homebox" postinst script returned status 1.
 * opkg_configure: homebox.postinst returned 1.
Fetch feed list for x86_64
Update feeds index
Downloading https://istore.linkease.com/repo/all/nas_luci/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_nas_luci
Downloading https://istore.linkease.com/repo/all/store/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_store
Downloading https://istore.linkease.com/repo/x86_64/nas/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_nas
Downloading https://istore.linkease.com/repo/all/compat/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/istore_compat
Downloading https://downloads.openwrt.org/snapshots/targets/x86/64/packages/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_core
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/base/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_base
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/luci/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_luci
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_packages
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/routing/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_routing
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_telephony
Downloading https://istore.linkease.com/repo/all/meta/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_meta
Try origin server https://istore.linkease.com/repo
Package app-meta-homebox (1.0.0-1) installed in root is up to date.
Configuring homebox.
Collected errors:
 * pkg_run_script: package "homebox" postinst script returned status 1.
 * opkg_configure: homebox.postinst returned 1.

**Comment by ZqinKing** [comment]
同样的错误。

**Comment by ZqinKing** [comment]
研究了一下，忽略即可，和/lib/functions.sh脚本中执行了相同的动作。

**Comment by jjm2473** [comment]
忽略这个错误，是最新的openwrt的/lib/functions.sh的postinst改变了uci-defaults的执行顺序导致的，新的openwrt上会重复执行uci-defaults，但是第一次执行后已经删掉相应文件了，才出现找不到文件的错误。

**Comment by h910056902r** [comment]
求助!出现相同的错误，有没有解决方案？

**Comment by jjm2473** [comment]
更新了一些ipk，现在兼容24.10了，卸载重装试试
