### ISSUE TITLE
更新到iStore v0.1.26-2后全部软件还是无法显示

### ISSUE THREAD

**Issue by kokpk** [linkease/istore#148]
一直处于正在努力的获取数据...
<img width="353" alt="企业微信截图_20241113063341" src="https://github.com/user-attachments/assets/62f6d2f9-fd66-4d1c-ad39-1eccc902ed2f">

**Comment by jjm2473** [comment]
今天更新了前端的api。

**Comment by miaoxiaohu** [comment]
我这边也是这样，维护那显示最新了
![image](https://github.com/user-attachments/assets/cb22d637-dd4d-49fd-9596-392dc1a66945)

**Comment by jjm2473** [comment]
现在最新版本已经是0.1.27-3了

**Comment by jjm2473** [comment]
@miaoxiaohu 你先到首页检查网络是不是正常的

**Comment by cyj153** [comment]
![image](https://github.com/user-attachments/assets/f8e7353b-8815-46bc-8c3f-9ab75a18eccd)
![image](https://github.com/user-attachments/assets/1ad1d352-8859-48b3-b064-0660d645624f)
我也是这样
