### ISSUE TITLE
可以适配一下SNAPSHOT的apk商店了

### ISSUE THREAD

**Issue by xuanranran** [linkease/istore#152]

**Comment by jjm2473** [comment]
等release看看，现在apk还有些功能不满足istore，例如切换配置文件和缓存目录。如果openwrt那边不打算支持，可能就要我们改apk了。

**Comment by jjm2473** [comment]
openwrt 24.10 已经放弃切换到 apk 了

**Comment by xuanranran** [comment]
是master的SNAPSHOT，不是24.10的SNAPSHOT，24.10是最后一个支持ipk的版本

**Comment by xuanranran** [comment]
> openwrt 24.10 已经放弃切换到 apk 了

是master的SNAPSHOT，不是24.10的SNAPSHOT，24.10是最后一个支持ipk的版本

**Comment by jjm2473** [comment]
那就再说吧，还不打算搞apk，仓库都不兼容，而且apk的第三方软件源目前没法跟系统独立
