### ISSUE TITLE
安装报错： resolve_conffiles: Existing conffile

### ISSUE THREAD

**Issue by QuattroRunner** [linkease/istore#153]
完整报错内容：
 Configuring luci-app-store.
Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/istore is different from the conffile in the new package. The new conffile will be placed at /etc/config/istore-opkg.

完整执行内容：
 ./istore-reinstall.run
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   605  100   605    0     0   5328      0 --:--:-- --:--:-- --:--:--  5353
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 98987  100 98987    0     0   532k      0 --:--:-- --:--:-- --:--:--  534k
Fetch feed list for x86_64
Update feeds index
Downloading https://istore.istoreos.com/repo/all/nas_luci/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_nas_luci
Downloading https://istore.istoreos.com/repo/all/store/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_store
Downloading https://istore.istoreos.com/repo/x86_64/nas/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_nas
Downloading https://istore.istoreos.com/repo/all/compat/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/istore_compat
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/23.05.5/targets/x86/64/packages/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_core
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/23.05.5/packages/x86_64/base/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_base
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/23.05.5/packages/x86_64/luci/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_luci
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/23.05.5/packages/x86_64/packages/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_packages
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/23.05.5/packages/x86_64/routing/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_routing
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/23.05.5/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_telephony
Downloading https://istore.istoreos.com/repo/all/meta/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_meta
Removing package luci-lib-taskd from root...
Removing package luci-lib-xterm from root...
Installing luci-lib-taskd (1.0.20) to root...
Downloading https://istore.istoreos.com/repo/all/store/luci-lib-taskd_1.0.20_all.ipk
Installing luci-lib-xterm (4.18.0) to root...
Downloading https://istore.istoreos.com/repo/all/store/luci-lib-xterm_4.18.0_all.ipk
Package luci-lib-xterm (4.18.0) installed in root is up to date.
Configuring luci-lib-xterm.
Configuring luci-lib-taskd.
Removing package luci-app-store from root...
Not deleting modified conffile /etc/config/istore.
Installing luci-app-store (0.1.26-3) to root...
Downloading https://istore.istoreos.com/repo/all/store/luci-app-store_0.1.26-3_all.ipk
Configuring luci-app-store.
Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/istore is different from the conffile in the new package. The new conffile will be placed at /etc/config/istore-opkg.

环境：PVE下x86openwrt原版安装istore。openwrt的软件分区使用挂载扩容了软件包空间到sda3.
![image](https://github.com/user-attachments/assets/22cbe4be-7b41-4f25-a35c-4197785832ea)

本身获取run脚本，网络有问题，所以直接浏览器打开了run脚本，然后原样复制到tmp下面新建run文件执行的。
之后安装就一直提示这个问题。把etc/config下的istore开头的文件删除，再wget安装还是这样的提示，第一次提示找不到etc/config下的istore文件，再执行一次就如本文开头的报错，上周五凌晨还正常的，安装报错再重新执行命令之后也可以用。
周六前后再重新装openwrt然后装商店就变这样了。
一直怀疑是最近域名备案之类的原因，用过公告的修复脚本，也没有效果。

**Comment by QuattroRunner** [comment]
openwrt现在用的是中科大的源，是这个原因吗？官方源地址我已经搞没了。

**Comment by jjm2473** [comment]
> resolve_conffiles: Existing conffile /etc/config/istore is different from the conffile in the new package. The new conffile will be placed at /etc/config/istore-opkg.

这不是错误，只是告诉你已经存在配置文件，不会覆盖了

**Comment by QuattroRunner** [comment]
> > resolve_conffiles: Existing conffile /etc/config/istore is different from the conffile in the new package. The new conffile will be placed at /etc/config/istore-opkg.
> 
> 这不是错误，只是告诉你已经存在配置文件，不会覆盖了

明白了，谢谢。刚刚到家发现已经恢复了。
