### ISSUE TITLE
希望适配即将发布的稳定版openwrt 24.10所使用的apk包管理器。

### ISSUE THREAD

**Issue by Liz-Nozomi** [linkease/istore#156]
如题。openwrt已经发布了24.10-rc2，并且明确了24.10将会作为下一个稳定版存在，而此版本中使用apk包管理器取代了opkg。希望istore能适配apk包管理器。
（其实只是因为本人固件的玄学问题，找不到软件源了，但是内核版本又很高，包管理器还是opkg，所以更新不了更新的内核了）

**Comment by bcseputetto** [comment]
@Liz-Nozomi 请注意，24.10 并没有切换到 apk包管理器，snapshot开发快照源才是apk管理器。
https://downloads.openwrt.org/releases/24.10.0-rc2/targets/x86/64/kmods/6.6.63-1-fdf628e4ac1bbb67c9c54e22238868e0/
24.10.0-rc2 目前还是 opkg包管理器，源里还是 ipk软件包

**Comment by jjm2473** [comment]
对，24.10 放弃切换到apk了，可能会在25.xx才切换
