### ISSUE TITLE
istore 无法更新

### ISSUE THREAD

**Issue by dtapps** [linkease/istore#157]
国内IP(广东)的情况下，列表无法更新 但是浏览器可以访问

`
root@iStoreOS:~# opkg update
Downloading https://istore.istoreos.com/repo/all/compat/Packages.gz
curl: (6) Could not resolve host: istore.istoreos.com
*** Failed to download the package list from https://istore.istoreos.com/repo/all/compat/Packages.gz

Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.7/targets/x86/64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.7/targets/x86/64/packages/Packages.sig
Signature check passed.
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.7/packages/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.7/packages/x86_64/base/Packages.sig
Signature check passed.
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.7/packages/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.7/packages/x86_64/luci/Packages.sig
Signature check passed.
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.7/packages/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.7/packages/x86_64/packages/Packages.sig
Signature check passed.
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.7/packages/x86_64/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.7/packages/x86_64/routing/Packages.sig
Signature check passed.
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.7/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.7/packages/x86_64/telephony/Packages.sig
Signature check passed.
Collected errors:
 * opkg_download: Failed to download https://istore.istoreos.com/repo/all/compat/Packages.gz, curl returned 6.
 * opkg_download: Check your network settings and connectivity.
 `

**Comment by jjm2473** [comment]
执行`nslookup istore.istoreos.com`看看，如果有问题，再试试`nslookup istore.istoreos.com 223.5.5.5`

**Comment by ZeroFung** [comment]
> 执行`nslookup istore.istoreos.com`看看，如果有问题，再试试`nslookup istore.istoreos.com 223.5.5.5`

同广东IP，同浏览器可以访问但列表无法更新，执行上面的报`;; connection timed out; no servers could be reached`，求助，谢谢！

**Comment by jjm2473** [comment]
说明你的软路由自己的网络有问题啊，dns都失败了。
