### ISSUE TITLE
无法安装应用

### ISSUE THREAD

**Issue by jesson1971** [linkease/istore#158]
版本是最新的0.1.27-2，也可以ping通fw.koolshare.com，浏览器打开都没有问题，但是任何软件都安装不了，已有的软件更新也是，显示故障都是一样的：

Fetch feed list for aarch64_cortex-a53
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to istore.istoreos.com:443

**Comment by jjm2473** [comment]
1. 检查网络和系统时间是不是正常。
2. 如果用了翻墙插件，先关掉再试试，如果关掉以后正常，那就把 istoreos.com 加入翻墙插件白名单以免被代理
