### ISSUE TITLE
软件源无法获取更新

### ISSUE THREAD

**Issue by SuperZeRoo** [linkease/istore#160]
Downloading https://istore.istoreos.com/repo/all/compat/Packages.gz
Updated list of available packages in /var/opkg-lists/istore_compat
Downloading https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/targets/ipq807x/generic/packages/Packages.gz
*** Failed to download the package list from https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/targets/ipq807x/generic/packages/Packages.gz

Downloading https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/base/Packages.gz
*** Failed to download the package list from https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/base/Packages.gz

Downloading https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/istore/Packages.gz
*** Failed to download the package list from https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/istore/Packages.gz

Downloading https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/luci/Packages.gz
*** Failed to download the package list from https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/luci/Packages.gz

Downloading https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/nas/Packages.gz
*** Failed to download the package list from https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/nas/Packages.gz

Downloading https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/nas_luci/Packages.gz
*** Failed to download the package list from https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/nas_luci/Packages.gz

Downloading https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/packages/Packages.gz
*** Failed to download the package list from https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/packages/Packages.gz

Downloading https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/routing/Packages.gz
*** Failed to download the package list from https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/routing/Packages.gz

Downloading https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/telephony/Packages.gz
*** Failed to download the package list from https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/telephony/Packages.gz

Collected errors:
 * opkg_download: Failed to download https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/targets/ipq807x/generic/packages/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/base/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/istore/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/luci/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/nas/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/nas_luci/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/packages/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/routing/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://mirrors.ustc.edu.cn/openwrt/releases/19.07-SNAPSHOT/packages/aarch64_cortex-a53/telephony/Packages.gz, wget returned 8.
![屏幕截图 2024-12-22 110303](https://github.com/user-attachments/assets/049de5ba-51ca-4789-9d5e-944ba3581941)

**Comment by xhbsa** [comment]
我也是这样

**Comment by jjm2473** [comment]
这是你的固件的软件源问题，你应该找固件作者。

**Comment by jjm2473** [comment]
'19.07-SNAPSHOT' 早就没了，不知道你这是啥固件。
