### ISSUE TITLE
求助：如何替换软件源

### ISSUE THREAD

**Issue by thomaswcy** [linkease/istore#19]
作为一名固件开发者，我非常希望能够在我的固件中内置 iStore，可惜 iStore 现阶段所包含的插件是在过少。op.supes.top 包含了现在绝大多数的 LuCI 的插件，我希望能够将这个网站作为 iStore 的软件源。想请问一下：
1. 有没有可能把 op.supes.top 作为 iStore 的软件源？
2. 如果 op.supes.top 可以做为 iStore 的软件源，那么我应该修改代码的哪些部分，让 iStore 将 op.supes.top 作为软件源？
如果能够回复，我将不胜感激。

**Comment by jjm2473** [comment]
is-opkg里面定义了istore软件源，系统自带软件源在 /etc/opkg/*

**Comment by jjm2473** [comment]
但是istore显示的所有软件不是从软件源里面获取的，而是在服务器上自己维护的另一套元数据

**Comment by jaqueline-law** [comment]
这种情况下，个人用户就被绑架到了istore上了，会有强行喂屎的风险，和梅林的爱酷商店就成了一丘之貉。

**Comment by jjm2473** [comment]
> 这种情况下，个人用户就被绑架到了istore上了，会有强行喂屎的风险，和梅林的爱酷商店就成了一丘之貉。

如果你要自己搭建服务器也可以啊，fork `https://github.com/linkease/istore-ui` 并把接口的服务器改成你自己的就行了，应该不用我教吧？

**Comment by thomaswcy** [comment]
我指的就是如何替换iStore 放元数据的服务器 为 op.supes.top

**Comment by jannson** [comment]
> 这种情况下，个人用户就被绑架到了istore上了，会有强行喂屎的风险，和梅林的爱酷商店就成了一丘之貉。

过分了，我们 Merlin 固件啥时候喂屎给你了？

**Comment by thomaswcy** [comment]
> > 这种情况下，个人用户就被绑架到了istore上了，会有强行喂屎的风险，和梅林的爱酷商店就成了一丘之貉。
> 
> 过分了，我们 Merlin 固件啥时候喂屎给你了？

我也无语呀，梅林什么时候喂屎了，我看是他给梅林喂屎

**Comment by jannson** [comment]
你要让 iStore 支持更多的插件，核心是这个：

https://github.com/linkease/openwrt-app-meta

这个是项目的元数据，你可以把元数据写入到路由器本地。这个我看已经有人成功了。我们人力很有限，无法提供更多的技术支持。

**Comment by thomaswcy** [comment]
> 你要让 iStore 支持更多的插件，核心是这个：
> 
> https://github.com/linkease/openwrt-app-meta
> 
> 这个是项目的元数据，你可以把元数据写入到路由器本地。这个我看已经有人成功了。我们人力很有限，无法提供更多的技术支持。
ok. Thanks.

**Comment by jjm2473** [comment]
要添加软件源，可以在luci的"软件包"页面编辑自定义软件源，istore也会使用这些系统配置的源

**Comment by thomaswcy** [comment]
抱歉打扰
1. bug反馈
使用 21.02 官方源码，见图
<img width="1440" alt="图片" src="https://user-images.githubusercontent.com/62056970/169762330-2ff38410-25dd-4512-8332-9c25682fe556.png">
各种yan'zhong错误，quickstart无法使用
2. 图标显示错误
还是见之前这张图
3. 元数据写入方式我看懂了，但插件的ipk该放在哪里？

**Comment by jjm2473** [comment]
浏览器调试看看网络请求，哪个接口404，是不是使用了不兼容的前后端？有没有安装luci-compat包？


ipk放在 https://github.com/linkease/istore-repo
