### ISSUE TITLE
istore提示更新，但是无效

### ISSUE THREAD

**Issue by HiJwm** [linkease/istore#20]
istore提示有更新，但是实际无法更新。望老大可以解决。

**Comment by jjm2473** [comment]
测试了可以更新到0.1.9，如果不能更新，终端执行 `is-opkg check_self_upgrade ; is-opkg do_self_upgrade` 看看输出什么

**Comment by guaotiantang** [comment]
curl: (22) The requested URL returned error: 404

**Comment by guaotiantang** [comment]
> 

curl: (22) The requested URL returned error: 404

**Comment by jjm2473** [comment]
执行 `grep ISTORE_INDEX= /bin/is-opkg` 看看结果

**Comment by guaotiantang** [comment]
ISTORE_INDEX=https://istore.linkease.com/repo/all/store/Packages.gz

里面的package:
Package: luci-app-store
Version: 0.1.9-1
Depends: libc, curl, opkg, luci-lib-ipkg, tar, coreutils, coreutils-stat, libuci-lua, mount-utils
Section: luci
Architecture: all
Installed-Size: 85965
Filename: luci-app-store_0.1.9-1_all.ipk
Size: 86998
SHA256sum: 952bb62e7dc027436055b7126bfd4071876ea91bc476d0967493b60fd02a04cc
Description:  luci-app-store is a ipk store developed by LinkEase team

**Comment by jjm2473** [comment]
你们安装的istore可能不是官方的，执行这个命令看看 `is-opkg install luci-app-store`，把全部日志贴出来

**Comment by jjm2473** [comment]
确实是缓存导致的，要等一天才能更新

**Comment by jjm2473** [comment]
如果还没更新，执行 `is-opkg upgrade luci-app-store` 更新到最新版，以修复此问题
