### ISSUE TITLE
首页Aria2开启状态显示不准确

### ISSUE THREAD

**Issue by hongtaohot858** [linkease/istore#21]
通过istore安装并配置了Aria2，程序处于运行状态，且RPC能正常载入。但首页Aria2状态栏里始终显示的是“当前状态：未启动”

**Comment by jjm2473** [comment]
“首页”是属于quickstart项目的，请到这边反馈 https://github.com/linkease/nas-packages-luci/issues

**Comment by hyy34** [comment]
> 通过istore安装并配置了Aria2，程序处于运行状态，且RPC能正常载入。但首页Aria2状态栏里始终显示的是“当前状态：未启动”

我为什么无法连接呢？？

**Comment by jjm2473** [comment]
@hyy34 可能根本就没启动，或者前端的rpc配置与后端不匹配。如果是istoreos，首页上可以一键配置后端和前端（AriaNG）。
