### ISSUE TITLE
iStore更新公告

### ISSUE THREAD

**Issue by jjm2473** [linkease/istore#22]
## 0.1.13
1. 在系统opkg中增加兼容包，例如 kmod-inet-diag，kmod-ipt-socket 等

## 0.1.12
1. 软件列表使用网格布局，以自适应宽屏幕
2. 增加Docker相关的提示和标记
3. “已安装”页面支持置顶应用

## 0.1.11
使用新的日志组件

## 0.1.10
支持英文

## 0.1.9
本地备份支持选择设备

## 0.1.8
增加备份功能

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1964/1

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1984/6
