### ISSUE TITLE
有没有大佬能编译一个armv8的版本啊

### ISSUE THREAD

**Issue by Zayia** [linkease/istore#24]

**Comment by jjm2473** [comment]
istore是平台无关，架构无关的

**Comment by Zayia** [comment]
> istore是平台无关，架构无关的

咋安装呢

**Comment by jjm2473** [comment]
安装这里的ipk即可 https://istore.linkease.com/repo/all/store/

**Comment by Myoko** [comment]
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFE                                                                                                                                                             R. Using latest.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFE                                                                                                                                                             R. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or                                                                                                                                                              PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or                                                                                                                                                              PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or                                                                                                                                                              PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. U                                                                                                                                                             sing latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. U                                                                                                                                                             sing latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. U                                                                                                                                                             sing latest.
Unknown package 'luci-app-store'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-lib-ipkg for luci-app-                                                                                                                                                             store
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-store found                                                                                                                                                             , but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-store.

安装不了

**Comment by jjm2473** [comment]
opkg配置问题，怎么会不支持 `all` 架构？你的固件是基于openwrt的什么版本？

**Comment by jjm2473** [comment]
执行`opkg print-architecture`看看输出什么

**Comment by jjm2473** [comment]
哦，你的这个是找不到`luci-lib-ipkg`，执行 `ls -l /usr/lib/lua/luci/model/ipkg.lua` 看看有没有这个文件

**Comment by Zayia** [comment]
我这里提示Unknown package 'luci-app-store'.

**Comment by jjm2473** [comment]
看看有没有类似这句
> pkg_hash_check_unresolved: cannot find dependency luci-lib-ipkg for luci-app-store
