### ISSUE TITLE
将iStore更改为二级目录后，所有商店内软件不能安装

### ISSUE THREAD

**Issue by HiJwm** [linkease/istore#25]
由于一些主题对istore作为一级目录支持不是很好，所以更改在了“服务”目录下，但是更改完成后，应用商店内所有应用均不能安装，求教大佬，还需要修改哪个文件？谢谢！

**Comment by jjm2473** [comment]
建议还是用argon或者meterial主题，因为openwrt官方21版就有一个dashboard插件是在一级菜单的，如果主题没适配，dashboard插件也会有问题
