### ISSUE TITLE
手工安装插件，最后提示失败，错误1，请教一下大佬怎么解决~~

### ISSUE THREAD

**Issue by skycn216** [linkease/istore#27]
./install.sh: line 7: ss-local: not found
ln: libmbedcrypto.so.3: File exists
ln: libmbedcrypto.so.7: File exists

**Comment by jjm2473** [comment]
ss是在官方仓库的，如果你的固件没有加上官方仓库，可能就安装不了ss了。如果不用ss可以忽略这个错误
