### ISSUE TITLE
Aria2安装后启动报错

### ISSUE THREAD

**Issue by harvies** [linkease/istore#28]
对不起，请求的目标未找到。

No page is registered at '/admin/services'. If this url belongs to an extension, make sure it is properly installed. If the extension was recently installed, try removing the /tmp/luci-indexcache file.

无法调度: /cgi-bin/luci/admin/services/aria2

**Comment by jannson** [comment]
应该是 Aria2 插件的兼容性问题，可能入口地址根本不是 OpenWRT 官方提供的入口地址。

**Comment by jjm2473** [comment]
> 对不起，请求的目标未找到。
> 
> No page is registered at '/admin/services'. If this url belongs to an extension, make sure it is properly installed. If the extension was recently installed, try removing the /tmp/luci-indexcache file.
> 
> 无法调度: /cgi-bin/luci/admin/services/aria2

可能是因为没安装 luci-compat?
