### ISSUE TITLE
安装失败,错误码 256

### ISSUE THREAD

**Issue by boshi116** [linkease/istore#3]
插件安装失败,错误码 256

**Comment by jjm2473** [comment]
请提供完整日志

**Comment by jannson** [comment]
我估计是 DNS 问题。一般安装失败是这个，路由器里面没网络

**Comment by yellowcaicai** [comment]
正在安装插件
Unknown package 'app-meta-cpulimit'.

curl: (6) Could not resolve host: istore.linkease.com
Collected errors:
 * opkg_install_cmd: Cannot install package app-meta-cpulimit.

安装失败,错误码 256
这是域名挂了吗

**Comment by jjm2473** [comment]
你直接在设备上执行 nslookup istore.linkease.com 看看呗，是不是设备没配置dns，又没用dhcp客户端

**Comment by yellowcaicai** [comment]
> 你直接在设备上执行 nslookup istore.linkease.com 看看呗，是不是设备没配置dns，又没用dhcp客户端

我在虚拟机不行，装实体机可以了，谢谢

**Comment by welbywen** [comment]
虚拟机应该也是可以的，在lan接口下配置dns
