### ISSUE TITLE
使用lean的lede源码编译报错

### ISSUE THREAD

**Issue by GHLiuyb** [linkease/istore#30]
![Uploading error.jpg…]()

**Comment by GHLiuyb** [comment]
![error](https://user-images.githubusercontent.com/86706862/169693707-4bc53244-eef7-403e-bf42-e443a6442aa8.jpg)

**Comment by jjm2473** [comment]
需要luci-lib-ipkg，这个官方源码是有的，如果确认自己不需要这个包，那就创建一个空包来满足依赖

重复 https://github.com/linkease/istore/issues/26

**Comment by GHLiuyb** [comment]
好的，谢谢
