### ISSUE TITLE
iStore 更新失败 插件安装404

### ISSUE THREAD

**Issue by fatrnick** [linkease/istore#38]
Wed Jun 29 00:33:57 2022 daemon.notice procd: /etc/rc.d/S99openclash: OpenClash Already Start!
Wed Jun 29 00:33:57 2022 daemon.notice procd: /etc/rc.d/S99pushbot: pushbot is starting now ...
Wed Jun 29 00:33:57 2022 daemon.info qbittorrent: Instance "main" disabled.
Wed Jun 29 00:33:57 2022 daemon.notice procd: /etc/rc.d/S99qbittorrent: Command failed: Invalid argument
Wed Jun 29 00:33:57 2022 daemon.notice procd: /etc/rc.d/S99serverchan: serverchan is starting now ...
Wed Jun 29 00:33:58 2022 daemon.notice procd: /etc/rc.d/S99shairport-sync: amixer: Mixer attach default error: No such file or directory
Wed Jun 29 00:33:58 2022 daemon.notice procd: /etc/rc.d/S99shairport-sync: amixer: Mixer attach default error: No such file or directory
Wed Jun 29 00:33:58 2022 daemon.notice procd: /etc/rc.d/S99shairport-sync: amixer: Mixer attach default error: No such file or directory
Wed Jun 29 00:33:58 2022 cron.err crond[16107]: crond (busybox 1.35.0) started, log level 8
Wed Jun 29 00:33:59 2022 daemon.notice ttyd[16129]: ttyd 1.6.3 (libwebsockets 4.1.6-20211107-496-g679ae72af)
Wed Jun 29 00:33:59 2022 daemon.notice ttyd[16129]: tty configuration:
Wed Jun 29 00:33:59 2022 daemon.notice ttyd[16129]:   start command: /bin/login
Wed Jun 29 00:33:59 2022 daemon.notice ttyd[16129]:   close signal: SIGHUP (1)
Wed Jun 29 00:33:59 2022 daemon.notice ttyd[16129]:   terminal type: xterm-256color
Wed Jun 29 00:33:59 2022 daemon.notice ttyd[16129]: LWS: 4.1.6-20211107-496-g679ae72af, loglevel 7
Wed Jun 29 00:33:59 2022 daemon.notice ttyd[16129]: NET CLI SRV H1 H2 WS IPV6-off
Wed Jun 29 00:33:59 2022 daemon.notice ttyd[16129]:    /usr/lib/libwebsockets-evlib_uv.so
Wed Jun 29 00:33:59 2022 daemon.notice ttyd[16129]:  Using foreign event loop...
Wed Jun 29 00:33:59 2022 daemon.notice ttyd[16129]:  Listening on port: 7681
Wed Jun 29 00:33:59 2022 user.notice vpnbypass [16392]: service monitoring interfaces: wan vpn0
Wed Jun 29 00:34:04 2022 daemon.notice procd: /etc/rc.d/S99zerotier: disabled in config
Wed Jun 29 00:34:04 2022 daemon.info procd: - init complete -
Wed Jun 29 00:34:06 2022 user.notice root: iptvhelper: reloading
Wed Jun 29 00:34:06 2022 user.notice root: iptvhelper: stopped
Wed Jun 29 00:34:06 2022 user.notice root: iptvhelper: starting
Wed Jun 29 00:35:09 2022 user.warn igmpproxy[11270]: MRT_DEL_MFC; Errno(2): No such file or directory
Wed Jun 29 00:35:09 2022 user.warn igmpproxy[11270]: MRT_DEL_MFC; Errno(2): No such file or directory
Wed Jun 29 00:35:09 2022 user.warn igmpproxy[11270]: MRT_DEL_MFC; Errno(2): No such file or directory
Wed Jun 29 00:37:19 2022 user.warn igmpproxy[11270]: MRT_DEL_MFC; Errno(2): No such file or directory
Wed Jun 29 00:37:19 2022 user.warn igmpproxy[11270]: MRT_DEL_MFC; Errno(2): No such file or directory
Wed Jun 29 00:37:19 2022 user.warn igmpproxy[11270]: MRT_DEL_MFC; Errno(2): No such file or directory
Wed Jun 29 00:38:00 2022 user.warn igmpproxy[11270]: MRT_DEL_MFC; Errno(2): No such file or directory
Wed Jun 29 00:38:00 2022 user.warn igmpproxy[11270]: MRT_DEL_MFC; Errno(2): No such file or directory
Wed Jun 29 00:38:00 2022 user.warn igmpproxy[11270]: MRT_DEL_MFC; Errno(2): No such file or directory

**Comment by Eliminater74** [comment]
same problem here as well.

**Comment by jjm2473** [comment]
执行 `is-opkg do_self_upgrade` ，看看有啥错误信息

**Comment by ScientistPun** [comment]
curl: (6) Could not resolve host: istore.linkease.com

**Comment by jjm2473** [comment]
尝试能不能访问 https://istore.linkease.com/repo/

**Comment by 43887016** [comment]
可以正常打开https://istore.linkease.com/repo/
无法正常打开https://istore.linkease.com/
可以正常打开http://istore.linkease.com/

以下为日志
root@OpenWrt:~# is-opkg install 'app-meta-homeassistant'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    57  100    57    0     0    278      0 --:--:-- --:--:-- --:--:--   283
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124  100   124    0     0    587      0 --:--:-- --:--:-- --:--:--   590
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   146    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

root@OpenWrt:~# is-opkg do_self_upgrade
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    57  100    57    0     0    259      0 --:--:-- --:--:-- --:--:--   271
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124  100   124    0     0    604      0 --:--:-- --:--:-- --:--:--   610
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   146    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

**Comment by jjm2473** [comment]
执行 `grep http /bin/is-opkg` 看看

**Comment by 43887016** [comment]
root@OpenWrt:~# grep http /bin/is-opkg
FEEDS_SERVER=https://istore.linkease.com/repo
ISTORE_INDEX=https://istore.linkease.com/repo/all/store/Packages.gz

**Comment by 43887016** [comment]
我是直接用22.03的官方版添加的此仓库的istore，并不是使用的istoreOS

**Comment by jjm2473** [comment]
执行 `opkg  print-architecture` 看看

**Comment by fatrnick** [comment]
root@CHA:~# opkg print-architecture
arch all 1
arch noarch 1
arch aarch64_generic 10
root@CHA:~# 

root@CHA:~# grep http /bin/is-opkg
FEEDS_SERVER=https://istore.linkease.com/repo
ISTORE_INDEX=https://istore.linkease.com/repo/all/store/Packages.gz


root@CHA:~# is-opkg do_self_upgrade
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    57  100    57    0     0    409      0 --:--:-- --:--:-- --:--:--   419
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124  100   124    0     0    871      0 --:--:-- --:--:-- --:--:--   892
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   146    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404


root@CHARHS:~# ping istore.linkease.com/repo/
PING istore.linkease.com/repo/ (198.18.15.237): 56 data bytes
64 bytes from 198.18.15.237: seq=0 ttl=64 time=0.614 ms
64 bytes from 198.18.15.237: seq=1 ttl=64 time=0.567 ms

**Comment by jjm2473** [comment]
我在仓库里加了兼容选项，现在应该可以了

**Comment by bootli** [comment]
> 我在仓库里加了了选项，现在应该可以了


最新版的iStore 编译出错WARNING: Makefile 'package/small-package/luci-app-store/Makefile' has a dependency on 'luci-lib-taskd', which does not exist

用lean大佬的源码5.4内核 缺少依赖 是不是要用官方源才可以编译
