### ISSUE TITLE
显示不正常

### ISSUE THREAD

**Issue by rq1025330** [linkease/istore#4]
![image](https://user-images.githubusercontent.com/52870887/143323139-cdb5c534-04c2-451f-af87-d9e0eb428eb8.png)
左侧错位 ，右侧不显示本地安装了的

**Comment by rq1025330** [comment]
应该是没居中

**Comment by rq1025330** [comment]
![image](https://user-images.githubusercontent.com/52870887/143323533-d148f8cb-a000-4d1e-808b-571a82689982.png)
只有这个正常

**Comment by jjm2473** [comment]
是主题的问题，很多主题渲染深度为1的菜单就会错误，只特定处理了“退出”按钮

**Comment by jannson** [comment]
需要修改下你主题的样式。需要支持这种顶级菜单的样式
