### ISSUE TITLE
NPC内网穿透 无法使用

### ISSUE THREAD

**Issue by cbsix888** [linkease/istore#40]
我下载了NPC  到 软路由里 设置成功也启动了 ，vps也安装成功了，

但我其它电脑上安装的 在NPC网页能看到   只有istore 这个不行   它不上线

请尽快解决下

**Comment by jjm2473** [comment]
NPC是什么

**Comment by cbsix888** [comment]
我写错了，是nps内网穿透，这个插件有问题
所有设置正确后，但网站后台显示离线



在 2022年8月8日星期一，练亮斌 ***@***.***> 写道：

**Comment by jjm2473** [comment]
istore没有上架nps啊

**Comment by jjm2473** [comment]
你用的istore是官方的吗

**Comment by cbsix888** [comment]
不知道啊 ，就不是有个X88的插件网站吗

练亮斌 ***@***.***> 于2022年8月11日周四 14:10写道：

**Comment by jjm2473** [comment]
那跟istore有啥关系，甚至不是istore的插件
