### ISSUE TITLE
iStore v0.1.12-4 版本更新以后 软件商店未安装成功

### ISSUE THREAD

**Issue by auaki** [linkease/istore#44]
![屏幕截图 2022-08-28 172104](https://user-images.githubusercontent.com/62469671/187067144-8ad00e50-cc44-4817-a8bc-d40e9b3b404f.jpg)
如图，
J1900 设备从0506在线升级至0715后，系统成功导入并运行，发现软件商店未安装成功，求无损解决方案，谢谢！

**Comment by jjm2473** [comment]
如果不是手动删除系统文件，我实在想不出什么情况下会出现文件丢失的问题
