### ISSUE TITLE
iStore 无法更新 及 安装APP 应用

### ISSUE THREAD

**Issue by wanglixiang90** [linkease/istore#47]
更新 iStore 和安装应用时 报错 404 ，无法正常使用iStore。
请问 iStore 后期还继续支持开源使用吗？

**Comment by jjm2473** [comment]
404？你的设备什么cpu的，可能不是istore官方软件仓库支持的cpu，目前支持的是x86_64和arm64

**Comment by wanglixiang90** [comment]
CPU：IPQ 40XX  ARM V7

**Comment by jjm2473** [comment]
istore官方的仓库没有支持ARM V7的软件包

**Comment by id10000** [comment]
> istore官方的仓库没有支持ARM V7的软件包
armv7
原来是这样，我也是404，哈哈
