### ISSUE TITLE
openwrt istore 无法更新及安装app应用

### ISSUE THREAD

**Issue by nankingcigar** [linkease/istore#50]
CPU: N5105
主系统：PVE 7.2-3
问题：
1. istore v0.1.11-1 维护 点我更新 升级0.1.12-7后，还是v.0.1.11-7 显示是成功的
2. 安装 rclone失败
截图
![image](https://user-images.githubusercontent.com/9410343/192651987-eac63bdc-b447-4f51-8433-a76adef46ab0.png)
![image](https://user-images.githubusercontent.com/9410343/192652023-59d18087-1898-4533-ac21-d8e510bb9118.png)
![image](https://user-images.githubusercontent.com/9410343/192652067-8ae610d9-af5c-4a8d-b3f5-3343f643e087.png)
![image](https://user-images.githubusercontent.com/9410343/192652119-36f1dbf8-5f3e-4874-ba29-7fe9659de64d.png)

**Comment by jjm2473** [comment]
看日志啊，kmod-fuse无法安装

**Comment by jjm2473** [comment]
kmod-fuse需要固件支持啊，不是istore的问题。kmod-开头的都是内核模块，要么固件本身打包好，要么固件提供可用的软件仓库。

**Comment by 396865270** [comment]
404
