### ISSUE TITLE
首页需要适配一下暗黑模式

### ISSUE THREAD

**Issue by Cineray** [linkease/istore#52]
现在的首页即便在暗黑模式下也是显示的亮色：

![Capture](https://user-images.githubusercontent.com/12690775/195495681-a62b1cfd-ca1b-4e75-88d6-6968e7e768a7.PNG)

并不是很舒适，建议可以换成暗色：

![Capture](https://user-images.githubusercontent.com/12690775/195495800-94396fbf-690e-4980-bbba-654fb3ebf757.PNG)

**Comment by jjm2473** [comment]
不同主题使用的变量不一样，首页没法知道现在是不是暗黑模式，如果你有方案也可以说一下

**Comment by pure-white-ice-cream** [comment]
> 不同主题使用的变量不一样，首页没法知道现在是不是暗黑模式，如果你有方案也可以说一下

两个方案，并不排斥，可以一起用

1、首页防止切换暗黑模式按钮
2、检测浏览器目前的暗黑模式主题（而不是美化ui）

先实现第一个比较简单，会让用户体验提升很多，非常感谢开发者~

**Comment by jjm2473** [comment]
早就实现暗色模式了
