### ISSUE TITLE
关于插件zerotier自建服务器的问题

### ISSUE THREAD

**Issue by liujixu1984** [linkease/istore#56]
使用软件中心的zerotier 由于需要替换planet文件，/etc/config/zero目录下替换节点不生效，我是替换/var/lib/zerotier-one文件夹下可以生效，但是每次替换后重启都会还原成默认的文件 请问如何避免？

**Comment by jjm2473** [comment]
现在应该修复了，注意 /etc/config/zero/interface.d 里面的文件还是会被替换。
如果不能满足你的需求，可以自己调用zerotier-one命令，在此之前执行`/etc/init.d/luci_zerotier disable ; /etc/init.d/luci_zerotier stop` 禁用默认的zerotier-one实例。
