### ISSUE TITLE
提示有更新，但更新报错

### ISSUE THREAD

**Issue by rockts** [linkease/istore#61]
<img width="741" alt="截屏2022-12-10 19 14 07" src="https://user-images.githubusercontent.com/9766196/206852217-b0fe5cbb-8162-40c2-b9c3-b2af979d0b01.png">
这是什么问题？
请问怎么解决？

**Comment by jjm2473** [comment]
你的固件不标准，想办法增加一个luci-lib-ipkg的空包，就能安装成功了
