### ISSUE TITLE
请开发大神能给适配下Station P2自带的WiFi驱动

### ISSUE THREAD

**Issue by xuma-input** [linkease/istore#63]
#### 设备一
**Station P2**，这款设备的自带WiFi芯片是**AP6245S**，CPU芯片**rk3568**，官方出的固件能驱动自带天线，第三方[DHDAXCW](https://github.com/DHDAXCW/Station_P2-M2) 这位大神的固件也能驱动，但第三方这位[DHDAXCW](https://github.com/DHDAXCW/Station_P2-M2) 大神的拨号无法使用。
#### 设备二
**R4S**，这款设备的官方FriendlyWrt固件是可以驱动**MT7612u**这个USB无线网卡的，官方支持列表中也有这个芯片型号，iStoreOS固件里我用**lsmod**查看模块也是有这个芯片驱动的，但就是不能够识别这个USB网卡。把官方固件道的驱动拉出来导入到iStoreOS里也是不能正常驱动。
##### 以上两个反馈，还请开发大神帮忙给支持一下，谢谢。

**Comment by jjm2473** [comment]
openwrt里面没有AP6245S相关驱动，如果有请提供驱动名称。
MT7612u也是openwrt官方的驱动，如果不支持也没办法。
我们不会移植wifi驱动，如果有需要可以自己去移植编译，反正项目都是开源的。

**Comment by jjm2473** [comment]
这个仓库是istore的，不是istoreos

**Comment by xuma-input** [comment]
明白了，感谢

**Comment by xuma-input** [comment]
MT7612u的驱动我自己想想办法；上面说错了，Station P2应该是AP6275S，只找到一个相关的txt，不知道是驱动源文件吗？
[brcmfmac43752-sdio.firefly,rk3568-roc-pc.txt](https://github.com/linkease/istore/files/10251592/brcmfmac43752-sdio.firefly.rk3568-roc-pc.txt)
