### ISSUE TITLE
内部服务器错误 500

### ISSUE THREAD

**Issue by cellistV** [linkease/istore#64]
对不起，服务器遇到未知错误。

/usr/lib/lua/luci/template.lua:97: Failed to execute template 'store/main'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:74: Failed to load template 'tasks/embed'.
Error while parsing template '/usr/lib/lua/luci/view/tasks/embed.htm':
No such file or directory
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:74: in function '__init__'
	/usr/lib/lua/luci/util.lua:65: in function 'Template'
	/usr/lib/lua/luci/dispatcher.lua:753: in function 'include'
	[string "/usr/lib/lua/luci/view/store/main.htm"]:3: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 
	(tail call): ?
	/usr/lib/lua/luci/controller/store.lua:134: in function

请问这种情况除了重刷固件，还有什么方式恢复

**Comment by jjm2473** [comment]
打开ssh或者ttyd，执行 `is-opkg install luci-lib-taskd` 应该可以修复

**Comment by weiqt** [comment]
遇到这个错误执行：is-opkg opkg install --force-reinstall taskd luci-lib-xterm

<img width="878" alt="image" src="https://user-images.githubusercontent.com/20502796/218957405-e2b6d69f-0b7d-4544-a5a5-a1266c61398e.png">

**Comment by codemenworld** [comment]
> is-opkg opkg install --force-reinstall taskd luci-lib-xterm luci-lib-taskd

没用，还是一样
