### ISSUE TITLE
小白请教如何在OpenWRT上安装istore

### ISSUE THREAD

**Issue by smallfish01** [linkease/istore#65]
谢谢。

**Comment by jjm2473** [comment]
最好是直接编译到固件里，而不是手动安装。如果要手动安装，下载这里 https://istore.linkease.com/repo/all/store/ 的所有ipk，然后放在设备上，例如 /tmp/upload , 然后执行 `opkg update; opkg install /tmp/upload/*.ipk` 应该就行了，如果页面上没显示istore，那再试试安装`opkg install luci-compat`

**Comment by smallfish01** [comment]
> 最好是直接编译到固件里，而不是手动安装。如果要手动安装，下载这里 https://istore.linkease.com/repo/all/store/ 的所有ipk，然后放在设备上，例如 /tmp/upload , 然后执行 `opkg update; opkg install /tmp/upload/*.ipk` 应该就行了，如果页面上没显示istore，那再试试安装`opkg install luci-compat`
非常感谢，因为是新手，从官网下载的镜像文件，我试试，再次谢谢您。

**Comment by smallfish01** [comment]
已安装完毕，谢谢！
