### ISSUE TITLE
请问如何安装在自己编译的固件上

### ISSUE THREAD

**Issue by usjinbao** [linkease/istore#69]
请问怎么在自己编译的固件上安装iStore应用商店，因为我需要用到一些例如wifi的功能 所以自己编译

**Comment by jjm2473** [comment]
添加到feed里面就行了啊，既然都会编译固件了，怎么会不知道怎么添加插件？

**Comment by jjm2473** [comment]
如果要安装到已刷好的固件里，安装这里的ipk即可 https://istore.linkease.com/repo/all/store/

**Comment by jjm2473** [comment]
https://github.com/linkease/istore#%E9%9B%86%E6%88%90%E5%88%B0%E8%87%AA%E5%B7%B1%E7%9A%84%E5%9B%BA%E4%BB%B6%E4%B8%AD
