### ISSUE TITLE
aarch64_cortex-a53 架构CPU安装插件提示404

### ISSUE THREAD

**Issue by iYongHsu** [linkease/istore#70]
![image](https://user-images.githubusercontent.com/28946326/217132847-a4e951a5-adfc-4079-ad9d-688d5fd45fe8.png)

**Comment by jjm2473** [comment]
执行 `jsonfilter -i /etc/.app_store.id -e '$.arch'` 看看。
还有 `opkg print-architecture | grep '^arch ' | grep -v 'arch all' | grep -v 'arch noarch' | sed -E 's/^arch ([^ ]+) (\d+)$/\2 \1/g' | sort -n -r`

**Comment by iYongHsu** [comment]
> 执行 看看。 还有 `jsonfilter -i /etc/.app_store.id -e '$.arch'``opkg print-architecture | grep '^arch ' | grep -v 'arch all' | grep -v 'arch noarch' | sed -E 's/^arch ([^ ]+) (\d+)$/\2 \1/g' | sort -n -r`

原始.app_store.id文件是aarch64_cortex-a53_neon，后面我自己修改为aarch64_cortex-a53就可以用了。

**Comment by jjm2473** [comment]
不对吧，istore会在启动时执行 `opkg print-architecture` ，然后找到数字最大的arch，从你发的opkg输出来看，应该会选择aarch64_cortex-a53，而不是aarch64_cortex-a53_neon

**Comment by jjm2473** [comment]
而且，有哪个设备会使用 aarch64_cortex-a53_neon 这个值，a53不是都支持neon的吗

**Comment by iYongHsu** [comment]
> 不对吧，istore会在启动时执行 `opkg print-architecture` ，然后找到数字最大的arch，从你发的opkg输出来看，应该会选择aarch64_cortex-a53，而不是aarch64_cortex-a53_neon

不太清楚哦，但是装完那个值确实有带neon。可能我是个例吧？

**Comment by softfuttery** [comment]
不是个例，请问怎么修改，遇到的问题一致


> > 执行 看看。 还有 `` jsonfilter -i /etc/.app_store.id -e '$.arch'``opkg print-architecture | grep '^arch ' | grep -v 'arch all' | grep -v 'arch noarch' | sed -E 's/^arch ([^ ]+) (\d+)$/\2 \1/g' | sort -n -r ``
> 
> 原始.app_store.id文件是aarch64_cortex-a53_neon，后面我自己修改为aarch64_cortex-a53就可以用了。

**Comment by jjm2473** [comment]
所以让你们执行 `opkg print-architecture | grep '^arch ' | grep -v 'arch all' | grep -v 'arch noarch' | sed -E 's/^arch ([^ ]+) (\d+)$/\2 \1/g' | sort -n -r` 看看啊，你们遇到问题的平台自己不执行，让我怎么排查bug

**Comment by softfuttery** [comment]
> 所以让你们执行 `opkg print-architecture | grep '^arch ' | grep -v 'arch all' | grep -v 'arch noarch' | sed -E 's/^arch ([^ ]+) (\d+)$/\2 \1/g' | sort -n -r` 看看啊，你们遇到问题的平台自己不执行，让我怎么排查bug

root@HandsomeMod:~# opkg print-architecture | grep '^arch ' | grep -v 'arch all' | grep -v 'arch noarch' | sed -E 's/^arch ([^ ]+) (\d+)$/\2 \1/
g' | sort -n -r
10 aarch64_cortex-a53_neon

root@HandsomeMod:~# jsonfilter -i /etc/.app_store.id -e '$.arch'
aarch64_cortex-a53_neon
照上方描述修改后
Package ppp-mod-pppoe version 2.4.8.git-2020-10-03-3 has no valid architecture, ignoring.
Package libconfig11 version 1.7.2-3 has no valid architecture, ignoring.
Package libnghttp2-14 version 1.43.0-1 has no valid architecture, ignoring.
Package coreutils-nohup version 8.32-6 has no valid architecture, ignoring.
Package kmod-ipt-nat version 5.10.33-1 has no valid architecture, ignoring.
Package dnsmasq-full version 2.85-5 has no valid architecture, ignoring.
Package python3-docker version 4.4.1-1 has no valid architecture, ignoring.
Unknown package 'app-meta-ddnsgo'.
Collected errors:
 * opkg_install_cmd: Cannot install package app-meta-ddnsgo.

**Comment by jjm2473** [comment]
@softfuttery 你的固件和机型是什么，为什么`opkg print-architecture`会输出`aarch64_cortex-a53_neon`，都没在openwrt代码里找到这个架构

**Comment by softfuttery** [comment]
> @softfuttery 你的固件和机型是什么，为什么`opkg print-architecture`会输出`aarch64_cortex-a53_neon`，都没在openwrt代码里找到这个架构

固件源码：https://github.com/HandsomeMod/HandsomeMod
设备：随身wifi，骁龙410，Qualcomm Msm89xx Soc

**Comment by jjm2473** [comment]
在仓库中把`aarch64_cortex-a53_neon`重定向到`aarch64_cortex-a53`了
