### ISSUE TITLE
arm_cortex-a9 架构CPU安装插件提示404

### ISSUE THREAD

**Issue by mice33** [linkease/istore#72]
<img width="781" alt="image" src="https://user-images.githubusercontent.com/4945433/220003202-1896f1cd-b4b0-49df-8a48-81f3ca435720.png">

设备是 斐讯  K3

**Comment by jjm2473** [comment]
istore官方仓库只支持arm64和x86_64，不支持arm32

**Comment by jjm2473** [comment]
就算能安装istore，大部分插件也是无法安装的
