### ISSUE TITLE
固件升级后，docker容器出现端口已用的，无法启动的情况，后发现是端口转发里启用了。

### ISSUE THREAD

**Issue by yejinxin123** [linkease/istore#73]
iStoreOS 21.02.3 2023021714
刚升级了固件，然后出现了jellyfin端口被占用无法启动的现象，后来发现是端口转发了开启了，然后关闭后，jellyfin可以正常启动了。这算个bug吧

**Comment by jjm2473** [comment]
socat转发的吗，那不算bug，本来就不能两个进程使用同一个端口

**Comment by yejinxin123** [comment]
那就只能先关闭socat的转发，然后先启动docker的容器后，再开启端口转发吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linkease/istore"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月21日(星期二) 晚上9:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linkease/istore] 固件升级后，docker容器出现端口已用的，无法启动的情况，后发现是端口转发里启用了。 (Issue #73)





 
socat转发的吗，那不算bug，本来就不能两个进程使用同一个端口

**Comment by jjm2473** [comment]
你到底想干嘛，socat端口转发以后，为什么这个端口还要用？一个端口要么就给socat转发，要么就给docker转发，不可能同时给转发到两个地方，你让内核怎么判断？
如果你要根据来源转发到不同的地方，那应该使用防火墙的转发功能，而不是socat
