### ISSUE TITLE
关于alist添加新用户后新用户可自行修改密码

### ISSUE THREAD

**Issue by xiaolongv** [linkease/istore#74]
添加过新用户后，用新用户登录后点击下方管理按钮就会跳转到个人资料界面，在这个界面新用户可自行修改账号密码，建议添加新用户修改账号密码的权限。

**Comment by jjm2473** [comment]
这里不是alist的仓库，请到alist官方仓库提议

**Comment by xiaolongv** [comment]
就是软路由里istore商店内的alist插件，官方那个好像没这问题
    
        
            
        
    
    
        
        

        
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年2月24日 21:26
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [linkease/istore] 关于alist添加新用户后新用户可自行修改密码 (Issue #74)
        
      
    
  
  

这里不是alist的仓库，请到alist官方仓库提议

**Comment by jjm2473** [comment]
alist启动以后就是官方的界面啊，跟商店已经没关系了。除非就是版本不一致，那之后更新可能就支持了

**Comment by xiaolongv** [comment]
ok了解，这就去官网反馈
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年2月25日 01:07
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [linkease/istore] 关于alist添加新用户后新用户可自行修改密码 (Issue #74)
        
      
    
  
  

alist启动以后就是官方的界面啊，跟商店已经没关系了。除非就是版本不一致，那之后更新可能就支持了
