### ISSUE TITLE
jellyfin插件安装后跳错误！没有适配页面！

### ISSUE THREAD

**Issue by mikejzy** [linkease/istore#79]
/usr/lib/lua/luci/dispatcher.lua:477: Failed to execute function dispatcher target for entry '/admin/services/jellyfin'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:477: Failed to execute cbi dispatcher target for entry '/admin/services/jellyfin/config'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/jellyfin.lua:13: attempt to index local 'obj' (a nil value)
stack traceback:
  [C]: in function 'assert'
  /usr/lib/lua/luci/dispatcher.lua:477: in function 'dispatch'
  /usr/lib/lua/luci/dispatcher.lua:129: in function </usr/lib/lua/luci/dispatcher.lua:128>

请问下是什么原因？

**Comment by jjm2473** [comment]
你的固件是什么版本？

**Comment by jjm2473** [comment]
你在软件包那边安装一下lsblk以后再试试

**Comment by mikejzy** [comment]
内核版本，5.15.94

**Comment by jjm2473** [comment]
跟内核没有关系。

**Comment by mikejzy** [comment]
使用的是恩山[sirpdboy]编译的固件。

**Comment by jjm2473** [comment]
在软件包那边安装一下lsblk以后再试试

**Comment by jjm2473** [comment]
之后会强制依赖lsblk

**Comment by mikejzy** [comment]
好的非常感谢，你们的商店非常好用，解决很多小白的问题，可惜就是科学插件没有，不过懂得都懂，本来就都用你们的固件了。

**Comment by mikejzy** [comment]
安装lsblk后，可以正常打开，已解决。

**Comment by jjm2473** [comment]
jellyfin插件已经增加了lsblk依赖，以免lsblk没安装
