### ISSUE TITLE
通过iSrore安装jellyfin后，无法启动，提示错误

### ISSUE THREAD

**Issue by mikejzy** [linkease/istore#80]
docker pull jellyfin/jellyfin
Using default tag: latest
latest: Pulling from jellyfin/jellyfin
Digest: sha256:97ae358b2f9091c6f745c47d9342cc615c73e3d672d8ac383385548afc836e28
Status: Image is up to date for jellyfin/jellyfin:latest
docker.io/jellyfin/jellyfin:latest
jellyfin
docker run --restart=unless-stopped -d -v "/opt/Configs/Jellyfin:/config"     --device /dev/dri:/dev/dri     --privileged     --dns=172.17.0.1     -p 8096:8096  -e TZ=Asia/Shanghai -v "/opt/Caches/Jellyfin:/config/transcodes" -v /mnt:/mnt --name jellyfin "jellyfin/jellyfin"
33a5e24dc1e388b61f076039bd3f710daa72c1bcdff6b9dd7803dc2efb417ee2
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: unable to retrieve OCI runtime error (open /var/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/33a5e24dc1e388b61f076039bd3f710daa72c1bcdff6b9dd7803dc2efb417ee2/log.json: no such file or directory): runc did not terminate successfully: exit status 2: unknown.

请问是插件商店安装的问题，还是固件编译者的问题？

**Comment by jjm2473** [comment]
那你执行 `docker run --restart=unless-stopped -d -v "/opt/Configs/Jellyfin:/config" --device /dev/dri:/dev/dri --privileged --dns=172.17.0.1 -p 8096:8096 -e TZ=Asia/Shanghai -v "/opt/Caches/Jellyfin:/config/transcodes" -v /mnt:/mnt --name jellyfin "jellyfin/jellyfin"` 看看呗

**Comment by mikejzy** [comment]
docker: Error response from daemon: Conflict. The container name "/jellyfin" is already in use by container "33a5e24dc1e388b61f076039bd3f710daa72c1bcdff6b9dd7803dc2efb417ee2". You have to remove (or rename) that container to be able to reuse that name.

**Comment by mikejzy** [comment]
错误依旧，
root@OpenWrt:~# docker rm -f jellyfin
jellyfin
root@OpenWrt:~# docker run --restart=unless-stopped -d -v "/opt/Configs/Jellyfin:/config" --device /dev/dri:/dev/dri --privileged --dns=172.17.0.1 -p 8096:8096 -e TZ
=Asia/Shanghai -v "/opt/Caches/Jellyfin:/config/transcodes" -v /mnt:/mnt --name jellyfin "jellyfin/jellyfin"
ad93429595ae5da906de4a96555e578af8429737e928415b63b975b0b8b336c2
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: unable to retrieve OCI runtime error (open /var/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/ad93429595ae5da906de4a96555e578af8429737e928415b63b975b0b8b336c2/log.json: no such file or directory): runc did not terminate successfully: exit status 2: unknown.

**Comment by jjm2473** [comment]
你的固件不会没有/var文件夹吧

**Comment by jjm2473** [comment]
你运行 `docker run hello-world` 看有没有报错吧
