### ISSUE TITLE
istores应用商店少个字

### ISSUE THREAD

**Issue by leige87** [linkease/istore#82]
![QQ图片20230319104635](https://user-images.githubusercontent.com/126918064/226154183-48ca77f6-6e22-434a-b13f-01cf677d8801.png)

**Comment by jjm2473** [comment]
下次发版会修复 https://github.com/linkease/istore/commit/4df864e7eeb75916ce39d1ab64bf02999fc77dcf

**Comment by leige87** [comment]
大概多久呀



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liangbin ***@***.***&gt;; 
发送时间: 2023年4月10日(星期一) 中午12:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [linkease/istore] istores应用商店少个字 (Issue #82)






下次发版会修复4df864e

—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by jjm2473** [comment]
就是下次有其他更新的时候一起带上，不会为了这一个字单独更新。或者我发个相同版本的，然后你重新安装就行了

**Comment by jjm2473** [comment]
先在istore里面安装 systools，以备不时之需。

联网的状态下，执行 `is-opkg update && is-opkg opkg install --force-reinstall luci-app-store`，就会更新到修复翻译的版本。

如果失败了，打开systools，里面有修复istore的工具，修复以后也是最新的版本。
