### ISSUE TITLE
安装软件后显示 istore (任务不存在或已删除)

### ISSUE THREAD

**Issue by jeremyliseismic** [linkease/istore#83]
istore版本：0.1.13-2
我装了一个smartdns之后就出现了这个黑框，并且还关不掉，求一个解决方法
![QQ图片20230328193310](https://user-images.githubusercontent.com/60601347/228225503-c47587de-f198-4570-9fa5-54ac4824b629.png)

**Comment by jjm2473** [comment]
重启试试
