### ISSUE TITLE
远程访问首页报错，其他页面正常

### ISSUE THREAD

**Issue by JamesWDGu** [linkease/istore#84]
通过 luci-app-ipsec-server 链接入内网，访问首页报错，如下图。其他页面正常

![CleanShot 2023-03-28 at 20 29 43](https://user-images.githubusercontent.com/55134047/228236621-3a80bab7-113b-407a-96d9-90f23ab6464b.png)

![CleanShot 2023-03-28 at 20 31 15](https://user-images.githubusercontent.com/55134047/228236772-4af6e3d2-53fd-4503-bfeb-771ceec8c654.png)

**Comment by jjm2473** [comment]
新版本已经修复了，这个问题是openwrt的uhttpd的bug导致的，新版本绕过了它的bug。 
uhttpd的bug信息在这里 https://github.com/openwrt/openwrt/pull/12388
