### ISSUE TITLE
iStore Memos升级镜像重新部署后内置的文档全部丢失。

### ISSUE THREAD

**Issue by vaecebyZ** [linkease/istore#85]
问题：
Memos docker配置页面貌似没有把Memos的文档储存做持久化。
只要一升级就会销毁掉当前container导致在container内的数据无法在更新后恢复。
![image](https://user-images.githubusercontent.com/45579121/231091538-9fbf7c51-b5ad-436a-b106-4380856af274.png)
![image](https://user-images.githubusercontent.com/45579121/231091875-76be4e8f-357e-41d3-b977-5e66d6d78695.png)

版本：
iStore [v0.1.13-2]
iStoreOS [ 21.02.3 2023040712]

**Comment by jjm2473** [comment]
我看看，可能是部署脚本写错了

**Comment by jjm2473** [comment]
修复了，等下istore有更新升级下。
不过之前的容器已经删除，数据没法恢复了，插件升级时会自动备份最后一次部署的容器的数据到新的配置文件夹。

**Comment by vaecebyZ** [comment]
没有计划让用户选择一个持久化位置？如果只是在升级时候才备份的话，docker>容器页面 勾选后删除按钮没有二次提醒也会导致误删除哦。 

> 修复了，等下istore有更新升级下。 不过之前的容器已经删除，数据没法恢复了，插件升级时会自动备份最后一次部署的容器的数据到新的配置文件夹。

**Comment by jjm2473** [comment]
不会的，那个只是删容器，数据还是保留在config目录，你在插件页面重新部署下就能回到之前的状态

**Comment by jjm2473** [comment]
我说的“在升级时候备份”是专门处理之前有bug的脚本产生的容器，之后不会再用到，以后升级插件或容器都不会再用到。插件升级以后，自然就不会再创建出有bug的容器，那也就不需要了。
