### ISSUE TITLE
发现手动安装的插件无法显示

### ISSUE THREAD

**Issue by kygsmsc** [linkease/istore#86]
iStore v0.1.13-2 自己在商店中手动安装的插件不管是RUN或是ipk都无法在已安装中显示，望能在下次更新中改进。

**Comment by jjm2473** [comment]
istore需要元数据才能显示，自己安装的一般没有元数据，只能在“软件包”界面管理。

如果有意贡献元数据，可以参考 https://github.com/linkease/openwrt-app-meta/
