### ISSUE TITLE
系统启动后串口没有任何输出

### ISSUE THREAD

**Issue by liudaobenyuan** [linkease/istore#87]
版本：iStoreOS 21.02.3 2023042111 / LuCI istoreos-21.02 branch git-23.088.34636-f8cc111
架构： x86/64
问题描述： rs232的串口没有只在grub启动阶段有输出，启动后没有任何输出，串口设置115200-8N1 
![image](https://user-images.githubusercontent.com/89021421/233774607-d3121744-47b2-4fae-8741-3914ac3c050d.png)

**Comment by jjm2473** [comment]
选择ttyS0啊。
默认不输出到串口，因为有些设备会卡死，自己选择ttyS0即可。

**Comment by liudaobenyuan** [comment]
bing搜索了下没找到怎么选择输出到ttyS0，麻烦指导下。

**Comment by jjm2473** [comment]
你自己截图的不是有个选项有ttyS0吗

**Comment by jjm2473** [comment]
GRUB菜单里面选择 ttyS0，就会输出到串口
