### ISSUE TITLE
D525的网络工控机不显示温度

### ISSUE THREAD

**Issue by liudaobenyuan** [linkease/istore#88]
sensors
coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +27.0°C  (crit = +100.0°C)
Core 1:       +26.0°C  (crit = +100.0°C)

drivetemp-scsi-0-0
Adapter: SCSI adapter
temp1:        +36.0°C  

![image](https://user-images.githubusercontent.com/89021421/234026584-4fe4b2eb-a27c-4cd2-b0b3-9dbf56f04ef0.png)

**Comment by jjm2473** [comment]
有些cpu的温度路径比较奇葩，不打算兼容
