### ISSUE TITLE
商店空白,正在努力獲取數據

### ISSUE THREAD

**Issue by Hadesaku** [linkease/istore#89]
版本iStore [v0.1.13-2] 軟件商店,  顯示空白,  一直是正在努力的獲取數據.........

**Comment by jjm2473** [comment]
是不是浏览器连不上服务器，在浏览器的网络调试窗口看看

**Comment by jjm2473** [comment]
如果浏览器不是Chrome，那先试试Chrome下有没有问题

**Comment by Hadesaku** [comment]
你好阿, Chrome浏览器也不行哦

**Comment by Hadesaku** [comment]
而且. 我也重新安装过了, 还是不行, 一直是正在努力的獲取數據

**Comment by Hadesaku** [comment]
你好,我想讓你知道, 我清除的瀏覽器的cookie之後, 現在正常了. 是什麽原因呢?  謝謝

**Comment by jjm2473** [comment]
页面上会请求 `https://istore.linkease.com/` 的API，用来获取软件列表，如果你的浏览器连接这个 API 站点有问题，那 iStore 上面就没法加载软件列表了。

我也不知道为啥你的浏览器cookie会影响。
