### ISSUE TITLE
istore (任务不存在或已删除)

### ISSUE THREAD

**Issue by ilxp** [linkease/istore#91]
21.02以及22.03和master上都是同样错误。无法关闭。

 https://www.right.com.cn/forum/data/attachment/forum/202305/08/140247e4wrjo33pj6dg8cw.png

**Comment by lkiuyu** [comment]
同样的错误，甚至安装istorex后无论点击路由还是nas都报object错误，控制台报的错点击去说是接口没注册

**Comment by lkiuyu** [comment]
重启完这个任务不存在的弹窗自然没了，但是只要安装或者卸载操作，都会出现任务不存在的弹窗，只有重启才能消失

**Comment by lkiuyu** [comment]
这个是istorex的错，istore的kong'zhi't控制台报错点进去和这个差不多
![1](https://github.com/linkease/istore/assets/8980816/d41823e3-8773-47a0-a0a3-05c61e33a20f)
![2](https://github.com/linkease/istore/assets/8980816/77fb0cd4-b4a6-4488-ba4d-d325b32bcf83)
![3](https://github.com/linkease/istore/assets/8980816/30ac58f0-5ea4-4f07-bb96-2e5d3661952d)

**Comment by jjm2473** [comment]
istore跟istorex的问题不要混为一谈！istorex原本就是给istoreos用的，自己不会看app的描述吗？如果要修复istorex的问题，需要在软件包那边卸载掉quickstart，然后重新安装istorex。

**Comment by jjm2473** [comment]
@ilxp 对于luci 21以上，需要安装 luci-compat

**Comment by jjm2473** [comment]
README不是写了21版本以上依赖 luci-compat 吗？ https://github.com/linkease/istore

**Comment by lkiuyu** [comment]
@jjm2473 你们的istorex的编译依赖项必选quickstart，编译的时候就带上了，启动后压根没出现选择界面只能手动又装了一遍istorex， luci-compat一直是装着的，istore依然是同样的问题，你的readme要的东西都有呢

**Comment by lkiuyu** [comment]
仓库一直最新的，主要是istore一直有上面的问题，装软件很难受，所以我就直接默认编译选上了itorex省的手动装了

**Comment by lkiuyu** [comment]
刚刚看了下istore有更新，我晚上回去同步一下源再编译看看

**Comment by jjm2473** [comment]
istore的问题，打开浏览器的网络调试窗口，看看有没有报错的请求

**Comment by lkiuyu** [comment]
我晚上回去截个图

**Comment by jjm2473** [comment]
我用OpenWRT官方的22.03.3和22.03.5测试了，完全没问题啊。

例如我刷的固件是 https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/openwrt-22.03.5-x86-64-generic-squashfs-combined-efi.img.gz

刷机后在终端里面执行：
```
opkg update;
cd /tmp;
wget https://github.com/linkease/openwrt-app-actions/raw/main/applications/luci-app-systools/root/usr/share/systools/istore-reinstall.run;
chmod 755 istore-reinstall.run;
./istore-reinstall.run;
```

然后就可以用了，没遇到任何问题。

**Comment by lkiuyu** [comment]
> 我用OpenWRT官方的22.03.3和22.03.5测试了，完全没问题啊。
> 
> 例如我刷的固件是 https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/openwrt-22.03.5-x86-64-generic-squashfs-combined-efi.img.gz
> 
> 刷机后在终端里面执行：
> 
> ```
> opkg update;
> cd /tmp;
> wget https://github.com/linkease/openwrt-app-actions/raw/main/applications/luci-app-systools/root/usr/share/systools/istore-reinstall.run;
> chmod 755 istore-reinstall.run;
> ./istore-reinstall.run;
> ```
> 
> 然后就可以用了，没遇到任何问题。

这个我也试了下，同样的问题

**Comment by jjm2473** [comment]
@lkiuyu 那你就别集成到固件，看看用我说的安装方式有没有问题。你要是不信也可以刷openwrt官方版本来测试

**Comment by jjm2473** [comment]
@lkiuyu 那你直接刷istoreos也有问题吗？

**Comment by lkiuyu** [comment]
@jjm2473 不是寻常的通用设备，是适配给骁龙410使用的，刷不了istoreos，目前是基于官方源码合并相关410支持来编译的，使用的6.1的内核，估计源码哪边还是有点问题，等有空再查查了

**Comment by jjm2473** [comment]
@lkiuyu 你还是看看系统日志有没有其他错误吧，会不会luci注册失败，或者luci-compat不是官方版本

**Comment by Beaverfffan** [comment]
确实是有这问题。只不过装还是正常装
![Uploading QQ截图20230523150158.png…]()

**Comment by Beaverfffan** [comment]
或许是架构标识问题。可能标aarch64或者a53不一样

**Comment by jjm2473** [comment]
如果架构标识问题，opkg应该会安装失败，错误是不兼容的架构
