### ISSUE TITLE
升级到0.1.13 后 菜单消失了

### ISSUE THREAD

**Issue by coolzhi** [linkease/istore#93]
升级到0.1.13 后 菜单消失了

对不起，请求的目标未找到。

No page is registered at '/admin/system/store'. If this url belongs to an extension, make sure it is properly installed. If the extension was recently installed, try removing the /tmp/luci-indexcache file.

无法调度: /cgi-bin/luci/admin/system/store/installed

**Comment by jjm2473** [comment]
官方的istore是在一级菜单的，你安装的不是官方版本。可能你增加了第三方的软件源，导致istore安装到了第三方版本。
